#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "cat $INDIR/I8/nums.txt | $BIN" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o68

echo "$?" >>$OUTDIR/o68

