#!/bin/bash -x

ps -e | grep vim-5.8 | cut -d' ' -f 1 | xargs -n 1 -I{} kill -s 9 {}

:<<EOF
if ps -p $pid > /dev/null; then
    echo "Process $pid still running after 10 seconds, sending SIGKILL..."
    kill -9 $pid
fi
EOF
