#!/bin/bash -x

# get the process IDs of all vim-5.8 processes that have been running for more than 2 mins
PIDS=$(ps -eo pid,etime,args | awk '$3~/vim-5.8/ && $2~/^[0-9][0-9]:/ {print $1}')

# Kill each process using SIGKILL
echo "$PIDS" | parallel --jobs 4 'kill -s 9 {}; '

if ps -p $pid > /dev/null; then
    echo "Process $pid still running after 10 seconds, sending SIGKILL..."
    kill -9 $pid
fi
