#!/bin/bash

DEBOP_DIR=/usr/local/debop
DEBOP_BIN=${DEBOP_DIR}/build/bin/reducer
iternum=100000000

realorcov=0 #1 means real, others mean cov
beta=0.5
version=1


for samplenum in 3000
do
    for k in 50
    do
	for alpha in 0.5
	do
	    ./run_debop ${realorcov} ${samplenum} ${iternum} ${alpha} ${beta} $k ${version}
	done
    done
done

