#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I0/tecmint-14-09-12.tar ./
cp -r $INDIR/I0/php ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rvf tecmint-14-09-12.tar php; } &>$OUTDIR/o9

echo "$?" >>$OUTDIR/o9
rm -fr php
tar xf tecmint-14-09-12.tar php


diff php/iframe_ew.php $INDIR/I0/php/iframe_ew.php
echo "$?" >>$OUTDIR/o9

diff php/videos_all.php $INDIR/I0/php/videos_all.php
echo "$?" >>$OUTDIR/o9

diff php/rss.php $INDIR/I0/php/rss.php
echo "$?" >>$OUTDIR/o9

diff php/index.php $INDIR/I0/php/index.php
echo "$?" >>$OUTDIR/o9

diff php/vendor.php $INDIR/I0/php/vendor.php
echo "$?" >>$OUTDIR/o9

diff php/video_title.php $INDIR/I0/php/video_title.php
echo "$?" >>$OUTDIR/o9

diff php/report.php $INDIR/I0/php/report.php
echo "$?" >>$OUTDIR/o9

diff php/video.php $INDIR/I0/php/video.php
echo "$?" >>$OUTDIR/o9

#I0