#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/etc ./
cp -r $INDIR/I7/opt ./
CURRDIR=$(pwd)

{ timeout -k 9 ${TIMEOUT}s $BIN -cpvf myarchive.tar $CURRDIR/etc/ $CURRDIR/opt/ --exclude=*.html; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm -fr etc
rm -fr opt
tar xf myarchive.tar
test -f ${leadpath}/opt/file.html
echo "$?" >>$OUTDIR/o58
diff ${leadpath}/etc/file $INDIR/I7/etc/file
echo "$?" >>$OUTDIR/o58


#I7