#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/archive.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN xfv archive.tar; } &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
diff file1 $INDIR/I4/file1
echo "$?" >>$OUTDIR/o37
diff file2 $INDIR/I4/file2
echo "$?" >>$OUTDIR/o37
diff file3 $INDIR/I4/file3
echo "$?" >>$OUTDIR/o37


#I4