#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I6/dir.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf dir.tar; } &>$OUTDIR/o50

echo "$?" >>$OUTDIR/o50
diff dir/file $INDIR/I6/dir/file
echo "$?" >>$OUTDIR/o50


#I6