#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/data.tar ./
cp -r $INDIR/I7/etc_fstab ./
CURRDIR=$(pwd)

{ timeout -k 9 ${TIMEOUT}s $BIN -rvf data.tar $CURRDIR/etc_fstab; } &>$OUTDIR/o54

echo "$?" >>$OUTDIR/o54

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm etc_fstab
tar xf data.tar
diff file $INDIR/I7/file
echo "$?" >>$OUTDIR/o54
diff ${leadpath}/etc_fstab $INDIR/I7/etc_fstab
echo "$?" >>$OUTDIR/o54




#I7