#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/ubuntu ./
CURRDIR=$(pwd)

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archive.tar $CURRDIR/ubuntu --exclude=$CURRDIR/ubuntu/Downloads --exclude=$CURRDIR/ubuntu/.cache; } &>$OUTDIR/o24

echo "$?" >>$OUTDIR/o24

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm -fr ubuntu

tar xf archive.tar
test -d ${leadpath}/ubuntu/Downloads
echo "$?" >>$OUTDIR/o24
test -f ${leadpath}/ubuntu/Downloads/song.mp3
echo "$?" >>$OUTDIR/o24
test -f ${leadpath}/ubuntu/Downloads/video.mp4
echo "$?" >>$OUTDIR/o24
test -f ${leadpath}/ubuntu/Downloads/image.png
echo "$?" >>$OUTDIR/o24
test -d ${leadpath}/ubuntu/.cache
echo "$?" >>$OUTDIR/o24

diff ${leadpath}/ubuntu/.ICEauthority $INDIR/I2/ubuntu/.ICEauthority
echo "$?" >>$OUTDIR/o24
diff ${leadpath}/ubuntu/stuff/test/file1 $INDIR/I2/ubuntu/stuff/test/file1
echo "$?" >>$OUTDIR/o24
diff ${leadpath}/ubuntu/stuff/test/file2 $INDIR/I2/ubuntu/stuff/test/file2
echo "$?" >>$OUTDIR/o24
diff ${leadpath}/ubuntu/archive.tar.gz $INDIR/I2/ubuntu/archive.tar.gz
echo "$?" >>$OUTDIR/o24
diff ${leadpath}/ubuntu/Documents/notes.txt $INDIR/I2/ubuntu/Documents/notes.txt
echo "$?" >>$OUTDIR/o24

test -d ${leadpath}/ubuntu/Videos
echo "$?" >>$OUTDIR/o24
test -d ${leadpath}/ubuntu/Pictures
echo "$?" >>$OUTDIR/o24
test -d ${leadpath}/ubuntu/Music
echo "$?" >>$OUTDIR/o24




#I2