#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file.tar ./
mkdir tmp

{ timeout -k 9 ${TIMEOUT}s $BIN xvf file.tar -C tmp; } &>$OUTDIR/o31

echo "$?" >>$OUTDIR/o31

if [ tmp/default.profraw ]; then
    cp tmp/default.profraw ./ #Important!
fi

diff tmp/os2.c $INDIR/I3/os2.c
echo "$?" >>$OUTDIR/o31
diff tmp/os3.c $INDIR/I3/os3.c
echo "$?" >>$OUTDIR/o31
diff tmp/os4.c $INDIR/I3/os4.c
echo "$?" >>$OUTDIR/o31

#I3