#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test3.tar ./
cp -r $INDIR/I8/test ./
cp -r $INDIR/I8/test1 ./
cp -r $INDIR/I8/test2 ./
cp -r $INDIR/I8/test3 ./
cp -r $INDIR/I8/test4 ./
echo "New text" >test

{ timeout -k 9 ${TIMEOUT}s $BIN --diff -f test3.tar test test1 test2 test3 test4; } &>$OUTDIR/o70

echo "$?" >>$OUTDIR/o70



#I8