#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I6/dir ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archiveToCreate.tar ./dir/*; } &>$OUTDIR/o49

echo "$?" >>$OUTDIR/o49
rm -fr ./dir
tar xf archiveToCreate.tar
diff dir/file $INDIR/I6/dir/file
echo "$?" >>$OUTDIR/o49


#I6