#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Latest ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf Videos.tar ./Latest/; } &>$OUTDIR/o17

echo "$?" >>$OUTDIR/o17
rm -fr Latest
tar xf Videos.tar
diff Latest/file $INDIR/I1/Latest/file
echo "$?" >>$OUTDIR/o17




#I1