#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN --extract -f test.tar test3; } &>$OUTDIR/o72

echo "$?" >>$OUTDIR/o72
diff test3 $INDIR/I8/test3
echo "$?" >>$OUTDIR/o72



#I8