#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test ./
cp -r $INDIR/I8/test1 ./
cp -r $INDIR/I8/test2 ./
cp -r $INDIR/I8/test3 ./
cp -r $INDIR/I8/test4 ./
cp -r $INDIR/I8/filenamenotcontainingtest ./
cp -r $INDIR/I8/testdir ./

{ timeout -k 9 ${TIMEOUT}s $BIN --create -f test2.tar * --exclude='file*'; } &>$OUTDIR/o620

echo "$?" >>$OUTDIR/o620
rm -fr test test1 test2 test3 test4 filenamenotcontainingtest testdir
tar xf test2.tar
diff test $INDIR/I8/test
echo "$?" >>$OUTDIR/o620
diff test1 $INDIR/I8/test1
echo "$?" >>$OUTDIR/o620
diff test2 $INDIR/I8/test2
echo "$?" >>$OUTDIR/o620
diff test3 $INDIR/I8/test3
echo "$?" >>$OUTDIR/o620
diff test4 $INDIR/I8/test4
echo "$?" >>$OUTDIR/o620
test -f filenamenotcontainingtest
echo "$?" >>$OUTDIR/o620

diff testdir/test $INDIR/I8/testdir/test
echo "$?" >>$OUTDIR/o620
diff testdir/test1 $INDIR/I8/testdir/test1
echo "$?" >>$OUTDIR/o620
diff testdir/test2 $INDIR/I8/testdir/test2
echo "$?" >>$OUTDIR/o620
diff testdir/test3 $INDIR/I8/testdir/test3
echo "$?" >>$OUTDIR/o620
diff testdir/test4 $INDIR/I8/testdir/test4
echo "$?" >>$OUTDIR/o620






#I8