#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/file.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xf file.tar; } &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
diff file $INDIR/I5/file
echo "$?" >>$OUTDIR/o46


#I5