#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/bigfile.tar ./
mkdir tmp

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf bigfile.tar -C tmp; } &>$OUTDIR/o11

if [ -f tmp/default.profraw ]; then
    cp tmp/default.profraw ./ #Important!
fi

echo "$?" >>$OUTDIR/o11
diff tmp/bigfile $INDIR/I1/bigfile
echo "$?" >>$OUTDIR/o11



#I1