#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Music.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xv -f Music.tar "new/two.mp3" "new/three.mp3"; } &>$OUTDIR/o14

echo "$?" >>$OUTDIR/o14
diff new/two.mp3 $INDIR/I1/new/two.mp3
echo "$?" >>$OUTDIR/o14
diff new/three.mp3 $INDIR/I1/new/three.mp3
echo "$?" >>$OUTDIR/o14



#I1