#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/folder ./
cp -r $INDIR/I4/upload ./
cp -r $INDIR/I4/file ./

{ timeout -k 9 ${TIMEOUT}s $BIN cfv archive.tar . --exclude='./folder' --exclude='./upload/folder2'; } &>$OUTDIR/o43

echo "$?" >>$OUTDIR/o43
rm -fr ./folder
rm -fr ./upload
rm -fr file

#Need to back up .profraw, as in this case, a partial .profraw file will be compressed, and then decompressed, and will overwrite the real one.
if [ -f default.profraw ]; then
    mv default.profraw default.profraw.backup
fi

tar xf archive.tar
test -d folder
echo "$?" >>$OUTDIR/o43
test -f folder/file
echo "$?" >>$OUTDIR/o43
test -d upload
echo "$?" >>$OUTDIR/o43
test -d upload/folder2
echo "$?" >>$OUTDIR/o43
test -f upload/folder2/file
echo "$?" >>$OUTDIR/o43
diff file $INDIR/I4/file
echo "$?" >>$OUTDIR/o43

if [ -f default.profraw.backup ]; then
    mv default.profraw.backup default.profraw
fi

#I4