#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I0/tecmint-14-09-12.tar ./
cp -r $INDIR/I0/xyz.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rvf tecmint-14-09-12.tar xyz.txt; } &>$OUTDIR/o8

echo "$?" >>$OUTDIR/o8
rm xyz.txt
tar xf tecmint-14-09-12.tar xyz.txt
diff xyz.txt $INDIR/I0/xyz.txt
echo "$?" >>$OUTDIR/o8

#I0