#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/file1 ./
cp -r $INDIR/I9/file2 ./
cp -r $INDIR/I9/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf file.tar file1 file2 file3; } &>$OUTDIR/o77

echo "$?" >>$OUTDIR/o77
rm file1 file2 file3
tar xf file.tar
diff file1 $INDIR/I9/file1
echo "$?" >>$OUTDIR/o77
diff file2 $INDIR/I9/file2
echo "$?" >>$OUTDIR/o77
diff file3 $INDIR/I9/file3
echo "$?" >>$OUTDIR/o77

#I9