#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/etc ./
cp -r $INDIR/I7/anaconda-ks.cfg ./
CURRDIR=$(pwd)

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf myarchive.tar $CURRDIR/etc $CURRDIR/anaconda-ks.cfg; } &>$OUTDIR/o51

echo "$?" >>$OUTDIR/o51

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm -fr etc
rm -fr anaconda-ks.cfg
tar xf myarchive.tar
diff ${leadpath}/etc/file $INDIR/I7/etc/file
echo "$?" >>$OUTDIR/o51
diff ${leadpath}/anaconda-ks.cfg $INDIR/I7/anaconda-ks.cfg
echo "$?" >>$OUTDIR/o51


#I7