#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

touch filei
{ timeout ${TIMEOUT}s echo "Y" | timeout ${TIMEOUT}s $BIN -i filei; }  &>$OUTDIR/o3
r=$?
if [[ $r -eq 0 && ! -f filei ]]; then
  echo  0 >$OUTDIR/o3
else
  clean
  echo  1 >$OUTDIR/o3
fi
touch filei
{ timeout ${TIMEOUT}s echo "N" | timeout ${TIMEOUT}s $BIN -i filei; }  &>$OUTDIR/o3
r=$?
if [[ $r -eq 0 && -f filei ]]; then
	echo  0 >$OUTDIR/o3
else
  	echo  1 >$OUTDIR/o3
fi
rm filei
