#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir dir
timeout ${TIMEOUT}s $BIN -r dir  &>$OUTDIR/o1
r=$?
a=1
b=1
if [[ $r -eq 0 && ! -d dir ]]; then
  a=0
fi
/bin/rm -rf dir
mkdir dir
timeout ${TIMEOUT}s $BIN -r -f dir  &>$OUTDIR/o1
r=$?
if [[ $r -eq 0 && ! -d dir ]]; then
  b=0
fi
/bin/rm -rf dir
if [[ $a -eq 0 && $b -eq 0 ]]; then
	echo  0 >$OUTDIR/o1
else
	echo  1 >$OUTDIR/o1
fi
