#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

touch file
timeout ${TIMEOUT}s $BIN file  &>$OUTDIR/o0
r=$?
a=1
b=1
if [[ $r -eq 0 && ! -f file ]]; then
  a=0
fi
/bin/rm -rf file
timeout ${TIMEOUT}s $BIN file  &>$OUTDIR/o0
r=$?
err=1
if grep -q "No such file or directory" $OUTDIR/o0; then
  err=0
fi
if [[ $r -eq 1 && $err -eq 0 ]]; then
  b=0
fi
if [[ $a -eq 0 && $b -eq 0 ]]; then
  echo  0 >$OUTDIR/o0 #Rewrite
else
  echo  1 >$OUTDIR/o0 #Rewrite
fi
