#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I5/sample3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN :sudo sample3; } &>$OUTDIR/o59

echo "$?" >>$OUTDIR/o59
own0=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o59

#parentI55