#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I4/file1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v ${uname} file1.txt; } &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
own0=`ls -al file1.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file1.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o37

#parentI42