#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I9/chownSample.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname}:sudo chownSample.txt; } &>$OUTDIR/o102

echo "$?" >>$OUTDIR/o102
own0=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o102

#parentI91