#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -L $INDIR/in.multinput  > $OUTDIR/o443 2>&1

cat lex.yy.c >> $OUTDIR/o443
cat error >> $OUTDIR/o443
