#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -df -Cre $INDIR/in.multrej  > $OUTDIR/o252 2>&1

cat lex.yy.c >> $OUTDIR/o252
cat error >> $OUTDIR/o252
