#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -d -Cae $INDIR/in.exp  > $OUTDIR/o663 2>&1

cat lex.yy.c >> $OUTDIR/o663
cat error >> $OUTDIR/o663
