#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -dl -Crae $INDIR/in.0  > $OUTDIR/o511 2>&1

cat lex.yy.c >> $OUTDIR/o511
cat error >> $OUTDIR/o511
