#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -F -Crae $INDIR/in.ch_exp_1  > $OUTDIR/o242 2>&1

cat lex.yy.c >> $OUTDIR/o242
cat error >> $OUTDIR/o242
