#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -dF -Cra $INDIR/in.ch  > $OUTDIR/o582 2>&1

cat lex.yy.c >> $OUTDIR/o582
cat error >> $OUTDIR/o582
