#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -dl -Crm $INDIR/in.exp  > $OUTDIR/o549 2>&1

cat lex.yy.c >> $OUTDIR/o549
cat error >> $OUTDIR/o549
