#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -S$INDIR/skel $INDIR/in.0  > $OUTDIR/o348 2>&1

cat lex.yy.c >> $OUTDIR/o348
cat error >> $OUTDIR/o348
cat skel >> $OUTDIR/o348
