#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -d -Caem $INDIR/in.closure  > $OUTDIR/o219 2>&1

cat lex.yy.c >> $OUTDIR/o219
cat error >> $OUTDIR/o219
