#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -T -fS$INDIR/skel $INDIR/in.0  > $OUTDIR/o529 2>&1

cat lex.yy.c >> $OUTDIR/o529
cat error >> $OUTDIR/o529
cat skel >> $OUTDIR/o529
