#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -df -Ca $INDIR/in.ch  > $OUTDIR/o571 2>&1

cat lex.yy.c >> $OUTDIR/o571
cat error >> $OUTDIR/o571
