#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

timeout -k 9 ${TIMEOUT}s $BIN error -df -Cae $INDIR/in.closure  > $OUTDIR/o310 2>&1

cat lex.yy.c >> $OUTDIR/o310
cat error >> $OUTDIR/o310
