#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-1a -k -p -s > $OUTDIR/o830 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o830
$INDIR/util/makeoutputcleanup $OUTDIR/o830
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o830

cat hello >> $OUTDIR/o830
cd ..
rm -r -f sdir
