#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16j ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN > $OUTDIR/o1532 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1532
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1532
cat make >> $OUTDIR/o1532
cd ..
rm -r -f sdir
