#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-1a -k -p -w > $OUTDIR/o304 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o304
$INDIR/util/makeoutputcleanup $OUTDIR/o304
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o304
cd ..
rm -r -f sdir
