#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-1a -k -p -s -w > $OUTDIR/o597 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o597
$INDIR/util/makeoutputcleanup $OUTDIR/o597
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o597

cat hello >> $OUTDIR/o597
cd ..
rm -r -f sdir
