#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -i -p -s > $OUTDIR/o1717 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1717
$INDIR/util/makeoutputcleanup $OUTDIR/o1717
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1717
cd ..
rm -r -f sdir
