#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -i -w > $OUTDIR/o1221 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o1221
$INDIR/util/makeoutputcleanup $OUTDIR/o1221
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1221
cd ..
rm -r -f sdir
