#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov3 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN - v - a > $OUTDIR/o281 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o281
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o281
cd ..
rm -r -f sdir
