#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10train/sdir-cov6 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN clean > $OUTDIR/o1830 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1830
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1830
cd ..
rm -r -f sdir
