#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -n > $OUTDIR/o1066 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o1066
$INDIR/util/makeoutputcleanup $OUTDIR/o1066
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1066

cat hello >> $OUTDIR/o1066
cd ..
rm -r -f sdir
