#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other3 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -p -f/dev/null > $OUTDIR/o1402 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1402
$INDIR/util/makeoutputcleanup $OUTDIR/o1402
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cd ..
rm -r -f sdir
