#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -i -n > $OUTDIR/o1419 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1419
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1419
cat hello >> $OUTDIR/o1419
cd ..
rm -r -f sdir
