#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10train/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10train/makefile-2a -k -n -p -s -w > $OUTDIR/o1828 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1828
$INDIR/util/makeoutputcleanup $OUTDIR/o1828
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1828

cat hello >> $OUTDIR/o1828
cd ..
rm -r -f sdir
