#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir3 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --file=$INDIR/n10test/makefilenoexist > $OUTDIR/o896 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o896
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cd ..
rm -r -f sdir
