#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16d ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN > $OUTDIR/o313 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o313
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o313
cat make >> $OUTDIR/o313
cd ..
rm -r -f sdir
