#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc8a ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -I ./include > $OUTDIR/o1212 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1212
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1212
cat hello >> $OUTDIR/o1212
cd ..
rm -r -f sdir
