#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10train/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10train/makefile-1a -i -n -p > $OUTDIR/o1827 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o1827
$INDIR/util/makeoutputcleanup $OUTDIR/o1827
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1827

cat hello >> $OUTDIR/o1827
cd ..
rm -r -f sdir
