#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -i -s > $OUTDIR/o360 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o360
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o360
cat hello >> $OUTDIR/o360
cd ..
rm -r -f sdir
