#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -n -p > $OUTDIR/o610 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o610
$INDIR/util/makeoutputcleanup $OUTDIR/o610
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o610
cd ..
rm -r -f sdir
