#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-2a -i -p -w > $OUTDIR/o1182 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1182
$INDIR/util/makeoutputcleanup $OUTDIR/o1182
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1182
cd ..
rm -r -f sdir
