#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-2a -i > $OUTDIR/o516 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o516
$INDIR/util/makeoutputcleanup $OUTDIR/o516
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o516
cd ..
rm -r -f sdir
