#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-2a -i -p -s > $OUTDIR/o672 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o672
$INDIR/util/makeoutputcleanup $OUTDIR/o672
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o672

cat hello >> $OUTDIR/o672
cd ..
rm -r -f sdir
