#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other3 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --old-file > $OUTDIR/o291 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o291
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o291
cd ..
rm -r -f sdir
