#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -k -n > $OUTDIR/o563 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o563
$INDIR/util/makeoutputcleanup $OUTDIR/o563
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o563
cd ..
rm -r -f sdir
