#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10train/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10train/makefile-2a -k -p -w > $OUTDIR/o1822 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1822
$INDIR/util/makeoutputcleanup $OUTDIR/o1822
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1822
cd ..
rm -r -f sdir
