#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -i -n > $OUTDIR/o654 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o654
$INDIR/util/makeoutputcleanup $OUTDIR/o654
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o654

cat hello >> $OUTDIR/o654
cd ..
rm -r -f sdir
