#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov7 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --file=Makefile --file=../sdir-cov8/Makefile > $OUTDIR/o526 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o526
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o526
cd ..
rm -r -f sdir
