#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -W hello.c > $OUTDIR/o457 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o457
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o457
cat hello >> $OUTDIR/o457
cd ..
rm -r -f sdir
