#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc3 ./sdir
timeout -k 9 ${TIMEOUT}s $BIN -C sdir -C baddirectory > $OUTDIR/o668 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o668
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

rm -r -f sdir
sed -i -n '$d' $OUTDIR/o668
