#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-2a > $OUTDIR/o1149 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o1149
$INDIR/util/makeoutputcleanup $OUTDIR/o1149
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1149

cat hello >> $OUTDIR/o1149
cd ..
rm -r -f sdir
