#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16f ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -p > $OUTDIR/o1241 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1241
$INDIR/util/makeoutputcleanup $OUTDIR/o1241
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1241

cat make >> $OUTDIR/o1241
cd ..
rm -r -f sdir
