#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -n -p -s > $OUTDIR/o623 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o623
$INDIR/util/makeoutputcleanup $OUTDIR/o623
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o623

cat hello >> $OUTDIR/o623
cd ..
rm -r -f sdir
