#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-1a -n -p > $OUTDIR/o649 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o649
$INDIR/util/makeoutputcleanup $OUTDIR/o649
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o649

cat hello >> $OUTDIR/o649
cd ..
rm -r -f sdir
