#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16c ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -p > $OUTDIR/o1188 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1188
$INDIR/util/makeoutputcleanup $OUTDIR/o1188
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1188

cat make >> $OUTDIR/o1188
cd ..
rm -r -f sdir
