#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov18 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -t > $OUTDIR/o1440 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1440
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cd ..
rm -r -f sdir
