#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -n -s -w > $OUTDIR/o387 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o387
$INDIR/util/makeoutputcleanup $OUTDIR/o387
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o387
cd ..
rm -r -f sdir
