#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-2a -i -n -p -w > $OUTDIR/o458 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o458
$INDIR/util/makeoutputcleanup $OUTDIR/o458
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o458

cat hello >> $OUTDIR/o458
cd ..
rm -r -f sdir
