#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -k -p -s -w > $OUTDIR/o212 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o212
$INDIR/util/makeoutputcleanup $OUTDIR/o212
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o212

cat hello >> $OUTDIR/o212
cd ..
rm -r -f sdir
