#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc3 ./sdir
timeout -k 9 ${TIMEOUT}s $BIN --directory=sdir --directory=baddirectory > $OUTDIR/o492 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o492
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

rm -r -f sdir
