#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10train/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10train/makefile-2a -k -p -s > $OUTDIR/o1826 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1826
$INDIR/util/makeoutputcleanup $OUTDIR/o1826
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1826
cd ..
rm -r -f sdir
