#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -n -p -s > $OUTDIR/o712 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o712
$INDIR/util/makeoutputcleanup $OUTDIR/o712
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o712

cat hello >> $OUTDIR/o712
cd ..
rm -r -f sdir
