#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -s -w > $OUTDIR/o1452 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o1452
$INDIR/util/makeoutputcleanup $OUTDIR/o1452
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1452
cd ..
rm -r -f sdir
