#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-1a -k -n -p > $OUTDIR/o1138 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1138
$INDIR/util/makeoutputcleanup $OUTDIR/o1138
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1138

cat hello >> $OUTDIR/o1138
cd ..
rm -r -f sdir
