#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -k -w > $OUTDIR/o549 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o549
$INDIR/util/makeoutputcleanup $OUTDIR/o549
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o549

cat hello >> $OUTDIR/o549
cd ..
rm -r -f sdir
