#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -i -n -p -w > $OUTDIR/o1141 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o1141
$INDIR/util/makeoutputcleanup $OUTDIR/o1141
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1141

cat hello >> $OUTDIR/o1141
cd ..
rm -r -f sdir
