#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16b ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN > $OUTDIR/o625 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o625
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat make >> $OUTDIR/o625
cd ..
rm -r -f sdir
