#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -i -p -s -w > $OUTDIR/o513 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o513
$INDIR/util/makeoutputcleanup $OUTDIR/o513
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o513

cat hello >> $OUTDIR/o513
cd ..
rm -r -f sdir
