#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc8 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -I $CURRDIR/sdir/include > $OUTDIR/o1237 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1237
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1237
cd ..
rm -r -f sdir
