#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
rm -f makefile
rm -f Makefile.in
timeout -k 9 ${TIMEOUT}s $BIN > $OUTDIR/o690 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o690
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
sed -i -n '$d' $OUTDIR/o690
fi

cat hello >> $OUTDIR/o690
cd ..
rm -r -f sdir
