#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -i -p -w > $OUTDIR/o1231 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o1231
$INDIR/util/makeoutputcleanup $OUTDIR/o1231
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1231

cat hello >> $OUTDIR/o1231
cd ..
rm -r -f sdir
