#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -i -n -p -w > $OUTDIR/o695 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o695
$INDIR/util/makeoutputcleanup $OUTDIR/o695
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o695

cat hello >> $OUTDIR/o695
cd ..
rm -r -f sdir
