#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -i -p -s > $OUTDIR/o993 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o993
$INDIR/util/makeoutputcleanup $OUTDIR/o993
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o993
cd ..
rm -r -f sdir
