#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc11 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -I ./include1/include2 > $OUTDIR/o107 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o107
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o107
cat hello >> $OUTDIR/o107
cd ..
rm -r -f sdir
