#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -p -s -w > $OUTDIR/o1749 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o1749
$INDIR/util/makeoutputcleanup $OUTDIR/o1749
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1749

cat hello >> $OUTDIR/o1749
cd ..
rm -r -f sdir
