#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other2 ./sdir
timeout -k 9 ${TIMEOUT}s $BIN -C sdir > $OUTDIR/o1433 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1433
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1433
sed -i -n '$d' $OUTDIR/o1433
rm -r -f sdir
