#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a > $OUTDIR/o510 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o510
$INDIR/util/makeoutputcleanup $OUTDIR/o510
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o510
cd ..
rm -r -f sdir
