#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -n > $OUTDIR/o857 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o857
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o857
cat hello >> $OUTDIR/o857
cd ..
rm -r -f sdir
