#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other2a ./sdir
timeout -k 9 ${TIMEOUT}s $BIN -C -f sdir $INDIR/n10test/Makefile-cov4 > $OUTDIR/o656 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o656
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

rm -r -f sdir
sed -i -n '$d' $OUTDIR/o656
