#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -i -p > $OUTDIR/o1628 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1628
$INDIR/util/makeoutputcleanup $OUTDIR/o1628
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1628

cat hello >> $OUTDIR/o1628
cd ..
rm -r -f sdir
