#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/grep1.dat $(pwd)/
timeout -k 9 ${TIMEOUT}s $BIN -n "/* The following list maps the names of the Posix named character classes static int laststart;True if we're separated from beginning or (, |" grep1.dat  > $OUTDIR/o496 2>&1

