#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/dump.doc ./
cp $INDIR/I8/file1 ./
cp $INDIR/I8/test.sh ./

{ timeout -k 9 ${TIMEOUT}s $BIN dump.doc file1 test.sh; } &>$OUTDIR/o71

echo "$?" >>$OUTDIR/o71
test -f dump.doc
echo "$?" >>$OUTDIR/o71
gzip -d <dump.doc.gz >rslt
cat rslt &>>$OUTDIR/o71

test -f file1
echo "$?" >>$OUTDIR/o71
gzip -d <file1.gz >rslt
cat rslt &>>$OUTDIR/o71

test -f test.sh
echo "$?" >>$OUTDIR/o71
gzip -d <test.sh.gz >rslt
cat rslt &>>$OUTDIR/o71


