#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/example ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 example; } &>$OUTDIR/o70

echo "$?" >>$OUTDIR/o70
test -f example
echo "$?" >>$OUTDIR/o70
gzip -d <example.gz >rslt
cat rslt &>>$OUTDIR/o70


