#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./

{ timeout -k 9 ${TIMEOUT}s $BIN helloworld; } &>$OUTDIR/o74

echo "$?" >>$OUTDIR/o74
test -f helloworld
echo "$?" >>$OUTDIR/o74
gzip -d <helloworld.gz >rslt
cat rslt &>>$OUTDIR/o74



