#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/linux-3.18.19.tar ./
gzip linux-3.18.19.tar

{ timeout -k 9 ${TIMEOUT}s $BIN -l linux-3.18.19.tar.gz; } &>$OUTDIR/o17

echo "$?" >>$OUTDIR/o17


