#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/test.sh ./

{ timeout -k 9 ${TIMEOUT}s $BIN -1 test.sh; } &>$OUTDIR/o55

echo "$?" >>$OUTDIR/o55
test -f test.sh
echo "$?" >>$OUTDIR/o55
gzip -d <test.sh.gz >rslt
cat rslt &>>$OUTDIR/o55


