#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/test.txt.gz ./

{ timeout -k 9 ${TIMEOUT}s $BIN -d test.txt.gz; } &>$OUTDIR/o49

echo "$?" >>$OUTDIR/o49
test -f test.txt.gz
echo "$?" >>$OUTDIR/o49
diff test.txt $INDIR/I4/test.txt >/dev/null
echo "$?" >>$OUTDIR/o49
