#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/mydoc.txt ./
gzip mydoc.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d mydoc.txt.gz; } &>$OUTDIR/o31

echo "$?" >>$OUTDIR/o31
test -f mydoc.txt.gz
echo "$?" >>$OUTDIR/o31
cat mydoc.txt &>>$OUTDIR/o31

