#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/mydoc.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -1 mydoc.txt; } &>$OUTDIR/o28

echo "$?" >>$OUTDIR/o28
test -f mydoc.txt
echo "$?" >>$OUTDIR/o28
gzip -d <mydoc.txt.gz >rslt
cat rslt &>>$OUTDIR/o28

