#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/dump.doc ./
cp $INDIR/I8/file1 ./
cp $INDIR/I8/test.sh ./
cat dump.doc file1 test.sh | gzip > all.gz

{ timeout -k 9 ${TIMEOUT}s $BIN -l all.gz; } &>$OUTDIR/o73

echo "$?" >>$OUTDIR/o73
