#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/examples.desktop ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v examples.desktop; } &>$OUTDIR/o66

echo "$?" >>$OUTDIR/o66
test -f examples.desktop
echo "$?" >>$OUTDIR/o66
gzip -d <examples.desktop.gz >rslt
cat rslt &>>$OUTDIR/o66
