#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/test.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN test.txt; } &>$OUTDIR/o42

echo "$?" >>$OUTDIR/o42
test -f test.txt
echo "$?" >>$OUTDIR/o42
gzip -d <test.txt.gz >rslt
cat rslt &>>$OUTDIR/o42

