#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./
cp $INDIR/I9/javaselightbox ./
gzip helloworld
gzip javaselightbox

#{ timeout -k 9 ${TIMEOUT}s $BIN -dr .; } &>$OUTDIR/o80
{ timeout -k 9 ${TIMEOUT}s $BIN -dr helloworld.gz javaselightbox.gz; } &>$OUTDIR/o80

echo "$?" >>$OUTDIR/o80
test -f helloworld.gz
echo "$?" >>$OUTDIR/o80
cat helloworld &>>$OUTDIR/o80

test -f javaselightbox.gz
echo "$?" >>$OUTDIR/o80
cat javaselightbox &>>$OUTDIR/o80
