#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/test.sh ./

{ timeout -k 9 ${TIMEOUT}s $BIN test.sh; } &>$OUTDIR/o50

echo "$?" >>$OUTDIR/o50
test -f test.sh
echo "$?" >>$OUTDIR/o50
gzip -d <test.sh.gz >rslt
cat rslt &>>$OUTDIR/o50


