#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/myfile1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f myfile1.txt; } &>$OUTDIR/o25

echo "$?" >>$OUTDIR/o25
test -f myfile1.txt
echo "$?" >>$OUTDIR/o25
gzip -d <myfile1.txt.gz >rslt
cat rslt &>>$OUTDIR/o25

