#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/mydoc.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v mydoc.txt; } &>$OUTDIR/o30

echo "$?" >>$OUTDIR/o30
test -f mydoc.txt
echo "$?" >>$OUTDIR/o30
gzip -d <mydoc.txt.gz >rslt
cat rslt &>>$OUTDIR/o30

