#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/examples.desktop ./

{ timeout -k 9 ${TIMEOUT}s $BIN examples.desktop; } &>$OUTDIR/o62

echo "$?" >>$OUTDIR/o62
test -f examples.desktop
echo "$?" >>$OUTDIR/o62
gzip -d <examples.desktop.gz >rslt
cat rslt &>>$OUTDIR/o62


