#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/test.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 test.txt; } &>$OUTDIR/o48

echo "$?" >>$OUTDIR/o48
test -f test.txt
echo "$?" >>$OUTDIR/o48
gzip -d <test.txt.gz >rslt
cat rslt &>>$OUTDIR/o48
