#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./
gzip helloworld

{ timeout -k 9 ${TIMEOUT}s $BIN -d helloworld.gz; } &>$OUTDIR/o77

echo "$?" >>$OUTDIR/o77
test -f helloworld.gz
echo "$?" >>$OUTDIR/o77
cat helloworld &>>$OUTDIR/o77
