#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 helloworld; } &>$OUTDIR/o76

echo "$?" >>$OUTDIR/o76
test -f helloworld
echo "$?" >>$OUTDIR/o76
gzip -d <helloworld.gz >rslt
cat rslt &>>$OUTDIR/o76
