#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file.txt ./
gzip file.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d file.txt.gz; } &>$OUTDIR/o16

echo "$?" >>$OUTDIR/o16
test -f file.txt.gz
echo "$?" >>$OUTDIR/o16
cat file.txt &>>$OUTDIR/o16

