#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file1.txt ./
cp $INDIR/I1/file2.txt ./
cp $INDIR/I1/file3.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1.txt file2.txt file3.txt; } &>$OUTDIR/o13

echo "$?" >>$OUTDIR/o13
test -f file1.txt
echo "$?" >>$OUTDIR/o13
gzip -d <file1.txt.gz >rslt
cat rslt &>>$OUTDIR/o13

test -f file2.txt
echo "$?" >>$OUTDIR/o13
gzip -d <file2.txt.gz >rslt
cat rslt &>>$OUTDIR/o13

test -f file3.txt
echo "$?" >>$OUTDIR/o13
gzip -d <file3.txt.gz >rslt
cat rslt &>>$OUTDIR/o13

