#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/test ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r test; } &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
test -f test/test.txt
echo "$?" >>$OUTDIR/o46
gzip -d <test/test.txt.gz >rslt
cat rslt >>$OUTDIR/o46

test -f test/test1.txt
echo "$?" >>$OUTDIR/o46
gzip -d <test/test1.txt.gz >rslt
cat rslt >>$OUTDIR/o46

