#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -c file.txt >file.txt.gz; } &>$OUTDIR/o14

echo "$?" >>$OUTDIR/o14
test -f file.txt
echo "$?" >>$OUTDIR/o14
gzip -d <file.txt.gz >rslt
cat rslt &>>$OUTDIR/o14

