#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/linux-3.18.19.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -1 linux-3.18.19.tar; } &>$OUTDIR/o18

echo "$?" >>$OUTDIR/o18
test -f linux-3.18.19.tar
echo "$?" >>$OUTDIR/o18
if [ -f linux-3.18.19.tar ]; then
    rm linux-3.18.19.tar
fi
gzip -d linux-3.18.19.tar.gz
diff linux-3.18.19.tar $INDIR/I1/linux-3.18.19.tar >/dev/null
echo "$?" >>$OUTDIR/o18

