#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/examples.desktop ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f examples.desktop; } &>$OUTDIR/o63

echo "$?" >>$OUTDIR/o63
test -f examples.desktop
echo "$?" >>$OUTDIR/o63
gzip -d <examples.desktop.gz >rslt
cat rslt &>>$OUTDIR/o63


