#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file ./

{ timeout -k 9 ${TIMEOUT}s $BIN -1 file; } &>$OUTDIR/o40

echo "$?" >>$OUTDIR/o40
test -f file
echo "$?" >>$OUTDIR/o40
gzip -d <file.gz >rslt
cat rslt &>>$OUTDIR/o40

