#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/test.sh ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 test.sh; } &>$OUTDIR/o56

echo "$?" >>$OUTDIR/o56
test -f test.sh
echo "$?" >>$OUTDIR/o56
gzip -d <test.sh.gz >rslt
cat rslt &>>$OUTDIR/o56


