#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/examples.desktop ./
gzip examples.desktop

{ timeout -k 9 ${TIMEOUT}s $BIN -l examples.desktop.gz; } &>$OUTDIR/o65

echo "$?" >>$OUTDIR/o65


