#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/file1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -5 file1.txt; } &>$OUTDIR/o61

echo "$?" >>$OUTDIR/o61
test -f file1.txt
echo "$?" >>$OUTDIR/o61
gzip -d <file1.txt.gz >rslt
cat rslt &>>$OUTDIR/o61


