#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 file; } &>$OUTDIR/o41

echo "$?" >>$OUTDIR/o41
test -f file
echo "$?" >>$OUTDIR/o41
gzip -d <file.gz >rslt
cat rslt &>>$OUTDIR/o41

