#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/example ./
cp $INDIR/I1/file1.txt ./
cp $INDIR/I1/file2.txt ./
cp $INDIR/I1/file3.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r $(pwd)/*; } &>$OUTDIR/o15

echo "$?" >>$OUTDIR/o15
test -f example/example.txt
echo "$?" >>$OUTDIR/o15
gzip -d <example/example.txt.gz >rslt
cat rslt &>>$OUTDIR/o15

test -f file1.txt
echo "$?" >>$OUTDIR/o15
gzip -d <file1.txt.gz >rslt
cat rslt &>>$OUTDIR/o15

test -f file2.txt
echo "$?" >>$OUTDIR/o15
gzip -d <file2.txt.gz >rslt
cat rslt &>>$OUTDIR/o15

test -f file3.txt
echo "$?" >>$OUTDIR/o15
gzip -d <file3.txt.gz >rslt
cat rslt &>>$OUTDIR/o15

