#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/* ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r *; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58
test -f file1.txt
echo "$?" >>$OUTDIR/o58
gzip -d <file1.txt.gz >rslt
cat rslt &>>$OUTDIR/o58

test -f file2.txt
echo "$?" >>$OUTDIR/o58
gzip -d <file2.txt.gz >rslt
cat rslt &>>$OUTDIR/o58

test -f file3.txt
echo "$?" >>$OUTDIR/o58
gzip -d <file3.txt.gz >rslt
cat rslt &>>$OUTDIR/o58

test -f file4.txt
echo "$?" >>$OUTDIR/o58
gzip -d <file4.txt.gz >rslt
cat rslt &>>$OUTDIR/o58


