#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/file ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f file; } &>$OUTDIR/o35

echo "$?" >>$OUTDIR/o35
test -f file
echo "$?" >>$OUTDIR/o35
gzip -d <file.gz >rslt
cat rslt &>>$OUTDIR/o35

