#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "tar cf - test/ | $BIN >test.tar.gz" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o72

echo "$?" >>$OUTDIR/o72
cp test/file ./
rm -fr test

tar zxf test.tar.gz
diff test/file file >/dev/null
echo "$?" &>>$OUTDIR/o72

rm run.sh
