#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/home ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r ./home/examples; } &>$OUTDIR/o67

echo "$?" >>$OUTDIR/o67
for i in {0..11}; do
    test -f ./home/examples/screenshot$i
    echo "$?" >>$OUTDIR/o67
    gzip -d <./home/examples/screenshot${i}.gz >rslt
    cat rslt &>>$OUTDIR/o67
done

