#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/examples.desktop ./
gzip examples.desktop

{ timeout -k 9 ${TIMEOUT}s $BIN -d examples.desktop.gz; } &>$OUTDIR/o64

echo "$?" >>$OUTDIR/o64
test -f examples.desktop.gz
echo "$?" >>$OUTDIR/o64
cat examples.desktop &>>$OUTDIR/o64


