#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/test1.txt ./
cp $INDIR/I4/test2.txt ./
cp $INDIR/I4/test3.txt ./
cp $INDIR/I4/test4.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN test1.txt test2.txt test3.txt test4.txt; } &>$OUTDIR/o44

echo "$?" >>$OUTDIR/o44
test -f test1.txt
echo "$?" >>$OUTDIR/o44
gzip -d <test1.txt.gz >rslt
cat rslt &>>$OUTDIR/o44

test -f test2.txt
echo "$?" >>$OUTDIR/o44
gzip -d <test2.txt.gz >rslt
cat rslt &>>$OUTDIR/o44

test -f test3.txt
echo "$?" >>$OUTDIR/o44
gzip -d <test3.txt.gz >rslt
cat rslt &>>$OUTDIR/o44

test -f test4.txt
echo "$?" >>$OUTDIR/o44
gzip -d <test4.txt.gz >rslt
cat rslt &>>$OUTDIR/o44

