#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/mydoc.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 mydoc.txt; } &>$OUTDIR/o29

echo "$?" >>$OUTDIR/o29
test -f mydoc.txt
echo "$?" >>$OUTDIR/o29
gzip -d <mydoc.txt.gz >rslt
cat rslt &>>$OUTDIR/o29

