#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/test.sh ./
gzip test.sh

{ timeout -k 9 ${TIMEOUT}s $BIN -d test.sh.gz; } &>$OUTDIR/o51

echo "$?" >>$OUTDIR/o51
test -f test.sh.gz
echo "$?" >>$OUTDIR/o51
cat test.sh &>>$OUTDIR/o51


