#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/example ./

{ timeout -k 9 ${TIMEOUT}s $BIN -1 example; } &>$OUTDIR/o69

echo "$?" >>$OUTDIR/o69
test -f example
echo "$?" >>$OUTDIR/o69
gzip -d <example.gz >rslt
cat rslt &>>$OUTDIR/o69


