#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./
gzip helloworld

{ timeout -k 9 ${TIMEOUT}s $BIN -dk helloworld.gz; } &>$OUTDIR/o78

echo "$?" >>$OUTDIR/o78
test -f helloworld.gz
echo "$?" >>$OUTDIR/o78
cat helloworld &>>$OUTDIR/o78
