#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/test.sh ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f test.sh; } &>$OUTDIR/o52

echo "$?" >>$OUTDIR/o52
test -f test.sh
echo "$?" >>$OUTDIR/o52
gzip -d <test.sh.gz >rslt
cat rslt &>>$OUTDIR/o52


