#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file1.txt ./
cp $INDIR/I1/file2.txt ./
gzip -c file1.txt >files.gz

{ timeout -k 9 ${TIMEOUT}s $BIN -c file2.txt >>files.gz; } &>$OUTDIR/o23

echo "$?" >>$OUTDIR/o23
test -f file2.txt
echo "$?" >>$OUTDIR/o23
gzip -d <files.gz >rslt
cat rslt >>$OUTDIR/o23
