#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/file1.txt ./
gzip file1.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d file1.txt.gz; } &>$OUTDIR/o59

echo "$?" >>$OUTDIR/o59
test -f file1.txt.gz
echo "$?" >>$OUTDIR/o59
cat file1.txt &>>$OUTDIR/o59


