#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/helloworld ./
cp $INDIR/I9/javaselightbox ./

#{ timeout -k 9 ${TIMEOUT}s $BIN -r .; } &>$OUTDIR/o79
{ timeout -k 9 ${TIMEOUT}s $BIN -r helloworld javaselightbox; } &>$OUTDIR/o79

echo "$?" >>$OUTDIR/o79
test -f helloworld
echo "$?" >>$OUTDIR/o79
gzip -d <helloworld.gz >rslt
cat rslt &>>$OUTDIR/o79

test -f javaselightbox
echo "$?" >>$OUTDIR/o79
gzip -d <javaselightbox.gz >rslt
cat rslt &>>$OUTDIR/o79
