#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file ./
cp -r $INDIR/I3/mydocument.odt ./
cp -r $INDIR/I3/"this is my file.png" ./
gzip file
gzip mydocument.odt
gzip "this is my file.png"

{ timeout -k 9 ${TIMEOUT}s $BIN -d *.gz; } &>$OUTDIR/o38

echo "$?" >>$OUTDIR/o38
test -f file.gz
echo "$?" >>$OUTDIR/o38
test -f mydocument.odt.gz
echo "$?" >>$OUTDIR/o38
test -f "this is my file.png".gz
echo "$?" >>$OUTDIR/o38

cat file &>>$OUTDIR/o38
cat mydocument.odt &>>$OUTDIR/o38
cat "this is my file.png" &>>$OUTDIR/o38

