#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/"this is my file.png" ./

{ timeout -k 9 ${TIMEOUT}s $BIN "this is my file.png"; } &>$OUTDIR/o33

echo "$?" >>$OUTDIR/o33
test -f "this is my file.png"
echo "$?" >>$OUTDIR/o33
gzip -d <"this is my file.png".gz >rslt
cat rslt &>>$OUTDIR/o33

