#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/dir ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r dir; } &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
test -f dir/file
echo "$?" >>$OUTDIR/o37
gzip -d <dir/file.gz >rslt
cat rslt &>>$OUTDIR/o37

