#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/dtmp ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r dtmp; } &>$OUTDIR/o53

echo "$?" >>$OUTDIR/o53
test -f dtmp/xyz
echo "$?" >>$OUTDIR/o53
test -f dtmp/abc
echo "$?" >>$OUTDIR/o53
gzip -d <dtmp/xyz.gz >rslt
cat rslt &>>$OUTDIR/o53
gzip -d <dtmp/abc.gz >rslt
cat rslt &>>$OUTDIR/o53


