#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/testfolder ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r testfolder; } &>$OUTDIR/o27

echo "$?" >>$OUTDIR/o27
test -f testfolder/file
echo "$?" >>$OUTDIR/o27
gzip -d <testfolder/file.gz >rslt
cat rslt &>>$OUTDIR/o27

