#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/mydocument.odt ./
gzip mydocument.odt

{ timeout -k 9 ${TIMEOUT}s $BIN -d mydocument.odt.gz; } &>$OUTDIR/o34

echo "$?" >>$OUTDIR/o34
test -f mydocument.odt.gz
echo "$?" >>$OUTDIR/o34
cat mydocument.odt &>>$OUTDIR/o34

