#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN file.txt >output.txt; } &>$OUTDIR/o12

echo "$?" >>$OUTDIR/o12
cat output.txt >>$OUTDIR/o12


