#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file5 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file5 -u >file5_duplicates.txt; } &>$OUTDIR/o114

echo "$?" >>$OUTDIR/o114
cat file5_duplicates.txt >>$OUTDIR/o114

