#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/file1 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1 -o output.txt; } &>$OUTDIR/o101

echo "$?" >>$OUTDIR/o101
cat output.txt >>$OUTDIR/o101

