#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/ls_l_usr_bin.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "cat ls_l_usr_bin.txt | $BIN -nr -k 5" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o69

echo "$?" >>$OUTDIR/o69

rm run.sh


