#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/table1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -k6 table1.txt >test_new.txt; } &>$OUTDIR/o83

echo "$?" >>$OUTDIR/o83
cat test_new.txt >>$OUTDIR/o83


