#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/ls_n.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "cat ls_n.txt | $BIN -t, -k5" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o84

echo "$?" >>$OUTDIR/o84

rm run.sh


