#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/datav1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN datav1.txt >output.txt; } &>$OUTDIR/o54

echo "$?" >>$OUTDIR/o54
cat output.txt >>$OUTDIR/o54

