#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/datav2.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "LC_ALL=C $BIN datav2.txt" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58

rm run.sh
