#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/data1.txt ./
cp $INDIR/I3/data2.txt ./
cp $INDIR/I3/data3.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "find -name \"data?.txt\" -print0 | $BIN --files0-from=-" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o60

echo "$?" >>$OUTDIR/o60

rm run.sh
