#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/datefile ./

timeout -k 9 ${TIMEOUT}s $BIN -r datefile &>output.txt
exit_val=$?

#Compare "UTC" and YEAR
info_to_compare=`head -1 output.txt | tr -s ' ' | cut -d' ' -f5,6`
>$OUTDIR/o59
#echo ${info_to_compare} &>$OUTDIR/o59
echo ${exit_val} >>$OUTDIR/o59
