#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

CURRDIR=$(pwd)
KNOUTDIR=${OUTDIR}/kn
UKNOUTDIR=${OUTDIR}/ukn

#Run known tests, input folder is the folder of postgresql
./run_test_kn.py $BIN $KNOUTDIR $TIMEOUT $INDIR

