#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp -r $INDIR/I3/sample ./
ln -s sample/ symbolic_folder
chown -R mychown:mychown symbolic_folder

{ timeout -k 9 ${TIMEOUT}s $BIN -R -H root symbolic_folder; } &>$OUTDIR/o25

echo "$?" >>$OUTDIR/o25
own0=`ls -al symbolic_folder | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al symbolic_folder | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o25

#parentI312
