#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I9/chownSample.txt ./
chown -R mychown:mychown chownSample.txt

{ timeout -k 9 ${TIMEOUT}s $BIN :sudo chownSample.txt; } &>$OUTDIR/o103

echo "$?" >>$OUTDIR/o103
own0=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o103

#parentI92
