#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp -r $INDIR/I8/Documents ./
cp -r $INDIR/I8/inbox ./

{ timeout -k 9 ${TIMEOUT}s $BIN -Rc --reference inbox Documents/work; } &>$OUTDIR/o91

echo "$?" >>$OUTDIR/o91
own0=`ls -al Documents/work | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al Documents/work | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o91


#parentI813