#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I4/greek1 ./
chown -R mychown:mychown greek1

{ timeout -k 9 ${TIMEOUT}s $BIN -v ${uname}:sudo greek1; } &>$OUTDIR/o39

echo "$?" >>$OUTDIR/o39
own0=`ls -al greek1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al greek1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o39

#parentI44
