#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I3/1.txt ./
cp $INDIR/I3/2.txt ./
chown :sudo 1.txt

{ timeout -k 9 ${TIMEOUT}s $BIN --reference=1.txt 2.txt; } &>$OUTDIR/o32

echo "$?" >>$OUTDIR/o32
own0=`ls -al 2.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al 2.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o32

#parentI37