#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I8/file2 ./
chown -R mychown:mychown file2

{ timeout -k 9 ${TIMEOUT}s $BIN :sudo file2; } &>$OUTDIR/o100

echo "$?" >>$OUTDIR/o100
own0=`ls -al file2 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file2 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o100


#parentI89
