#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I2/file1 ./
cp $INDIR/I2/file2 ./

chown ${uname}:sudo file1

{ timeout -k 9 ${TIMEOUT}s $BIN --reference=file1 file2; } &>$OUTDIR/o12

echo "$?" >>$OUTDIR/o12
own0=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o12

own0=`ls -al file2 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file2 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o12

#parentI210