#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I6/at.c ./
chown -R mychown:mychown at.c

{ timeout -k 9 ${TIMEOUT}s $BIN :sudo at.c; } &>$OUTDIR/o71

echo "$?" >>$OUTDIR/o71
own0=`ls -al at.c | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al at.c | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o71

#parentI67
