#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp -r $INDIR/I6/archive ./
chown -R mychown:mychown ./archive/

{ timeout -k 9 ${TIMEOUT}s $BIN -R ${uname} ./archive/; } &>$OUTDIR/o68

echo "$?" >>$OUTDIR/o68
own0=`ls -al ./archive/ | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al ./archive/ | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o68

#parentI64
