#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I3/1.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN root 1.txt; } &>$OUTDIR/o21

echo "$?" >>$OUTDIR/o21
own0=`ls -al 1.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al 1.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o21

#parentI30