#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I8/file1 ./
cp $INDIR/I8/file2 ./
cp $INDIR/I8/file3 ./
chown -R mychown:mychown file*

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname} file*; } &>$OUTDIR/o92

echo "$?" >>$OUTDIR/o92
own0=`ls -al file* | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file* | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o92

#parentI814
