#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I5/sample3 ./
chown -R mychown:mychown sample3

{ timeout -k 9 ${TIMEOUT}s $BIN --from=root:${uname} ${uname}:sudo sample3; } &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
own0=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o46

#parentI510
