#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I3/1.txt ./
ln -s 1.txt 1_link.txt
chown -R mychown:mychown 1_link.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -h root:sudo 1_link.txt; } &>$OUTDIR/o23

echo "$?" >>$OUTDIR/o23
own0=`ls -al 1_link.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al 1_link.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o23

#parentI310
