#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I9/chownSample.txt ./
ln -s chownSample.txt symlink
chown -R mychown symlink

{ timeout -k 9 ${TIMEOUT}s $BIN -h ${uname} symlink; } &>$OUTDIR/o109

echo "$?" >>$OUTDIR/o109
own0=`ls -al symlink | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al symlink | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o109

own0=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al chownSample.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o109



#parentI98
