#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I3/1.txt ./
chown -R mychown:mychown 1.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -f ${uname} 1.txt; } &>$OUTDIR/o31

echo "$?" >>$OUTDIR/o31
own0=`ls -al 1.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al 1.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o31

#parentI36
