#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I5/sample2 ./
cp $INDIR/I5/sample3 ./
chown -R mychown:mychown sample2 sample3

{ timeout -k 9 ${TIMEOUT}s $BIN root sample2 sample3; } &>$OUTDIR/o57

echo "$?" >>$OUTDIR/o57
own0=`ls -al sample2 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample2 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o57

own0=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o57

#parentI53
