#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp -r $INDIR/I7/linux ./
chown -R mychown:mychown linux

{ timeout -k 9 ${TIMEOUT}s $BIN -R ${uname}:sudo linux; } &>$OUTDIR/o85

echo "$?" >>$OUTDIR/o85
own0=`ls -al linux | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al linux | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o85

#parentI79
