#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
mkdir -p $(pwd)/TestUnix
chown -R mychown:mychown $(pwd)/TestUnix

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname} $(pwd)/TestUnix; } &>$OUTDIR/o104

echo "$?" >>$OUTDIR/o104
own0=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o104

chown -R root:root $(pwd)/TestUnix

#parentI93
