#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I4/greek1 ./
cp $INDIR/I4/greek2 ./
chown :sudo greek1

{ timeout -k 9 ${TIMEOUT}s $BIN -v --reference=greek1 greek2; } &>$OUTDIR/o42

echo "$?" >>$OUTDIR/o42
own0=`ls -al greek2 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al greek2 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o42

#parentI47