#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I7/file ./
cp $INDIR/I7/tmpfile ./
chown :sudo file

{ timeout -k 9 ${TIMEOUT}s $BIN --reference=file tmpfile; } &>$OUTDIR/o84

echo "$?" >>$OUTDIR/o84
own0=`ls -al tmpfile | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al tmpfile | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o84

#parentI78