#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I5/sample ./
chown -R mychown:mychown sample

{ timeout -k 9 ${TIMEOUT}s $BIN :${uid} sample; } &>$OUTDIR/o60

echo "$?" >>$OUTDIR/o60
own0=`ls -al sample | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o60

#parentI56
