#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I8/myfile.txt ./
chown -R mychown:mychown myfile.txt

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname} myfile.txt; } &>$OUTDIR/o86

echo "$?" >>$OUTDIR/o86
own0=`ls -al myfile.txt | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al myfile.txt | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o86

#parentI80
