#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)
uname=$(whoami)
mkdir -p $CURRDIR/foo
chown -R mychown:mychown $CURRDIR/foo
{ timeout -k 9 ${TIMEOUT}s $BIN -R root ${CURRDIR}/foo; } &>$OUTDIR/o6

echo "$?" >>$OUTDIR/o6
own0=`ls -al $(pwd)/foo | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/foo | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o6

chown -R root:root ${CURRDIR}/foo

#parentI06
