#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I5/sample2 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v ${uname} sample2; } &>$OUTDIR/o52

echo "$?" >>$OUTDIR/o52
own0=`ls -al sample2 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample2 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o52

#parentI516