#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
if [ -d $(pwd)/tmp/TestUnix ]; then
    chmod 755 -R $(pwd)/tmp/TestUnix
    rm -fr $(pwd)/tmp/TestUnix
fi
mkdir -p $(pwd)/tmp/TestUnix
cp $INDIR/I9/chownSample.txt $(pwd)/tmp/TestUnix/


{ timeout -k 9 ${TIMEOUT}s $BIN ${uname}:sudo /tmp/TestUnix/chownSample.txt $(pwd)/tmp/TestUnix; } &>$OUTDIR/o107

echo "$?" >>$OUTDIR/o107
own0=`ls -al $(pwd)/tmp/TestUnix | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/tmp/TestUnix | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o107

chmod 755 -R $(pwd)/tmp/TestUnix
rm -fr $(pwd)/tmp/TestUnix

#parentI96
