#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I5/sample3 ./
cp -r $INDIR/I5/Dir1 ./

{ timeout -k 9 ${TIMEOUT}s $BIN root sample3 Dir1; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58
own0=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample3 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o58

own0=`ls -al Dir1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al Dir1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o58

#parentI54