#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
mkdir -p $(pwd)/TestUnix
{ timeout -k 9 ${TIMEOUT}s $BIN ${uname}:sudo $(pwd)/TestUnix; } &>$OUTDIR/o106

echo "$?" >>$OUTDIR/o106
own0=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o106

chown -R root:root $(pwd)/TestUnix

#parentI95
