#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I6/charm.c ./

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname}:sudo charm.c; } &>$OUTDIR/o69

echo "$?" >>$OUTDIR/o69
own0=`ls -al charm.c | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al charm.c | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o69

#parentI65