#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)
uname=$(whoami)
uid=`id -u ${uname}`
mkdir -p $CURRDIR/foo/bar
{ timeout -k 9 ${TIMEOUT}s $BIN -R ${uname}: ${CURRDIR}/foo/bar; } &>$OUTDIR/o19

echo "$?" >>$OUTDIR/o19
own0=`ls -al $(pwd)/foo/bar | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/foo/bar | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o19

chown -R root:root ${CURRDIR}/foo/bar

#parentI28
