#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I7/tmpfile ./
ln -s tmpfile tmpfile_symlnk

{ timeout -k 9 ${TIMEOUT}s $BIN root:sudo tmpfile_symlnk; } &>$OUTDIR/o79

echo "$?" >>$OUTDIR/o79
own0=`ls -al tmpfile_symlnk | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al tmpfile_symlnk | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o79

own0=`ls -al tmpfile | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al tmpfile | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o79

#parentI73