#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I5/sample* ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v -R ${uname} sample*; } &>$OUTDIR/o53

echo "$?" >>$OUTDIR/o53
own0=`ls -al sample* | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al sample* | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o53

#parentI517