#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
mkdir -p $(pwd)/TestUnix
{ timeout -k 9 ${TIMEOUT}s $BIN -R ${uname} $(pwd)/TestUnix; } &>$OUTDIR/o110

echo "$?" >>$OUTDIR/o110
own0=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al $(pwd)/TestUnix | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o110

chown -R root:root $(pwd)/TestUnix

#parentI99
