#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -k -s -w > $OUTDIR/o1038 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o1038
$INDIR/util/makeoutputcleanup $OUTDIR/o1038
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1038

cat hello >> $OUTDIR/o1038
cd ..
rm -r -f sdir
