#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other2 ./sdir
timeout -k 9 ${TIMEOUT}s $BIN -C sdir > $OUTDIR/o989 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o989
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat sdir/hello >> $OUTDIR/o989
sed -i -n '$d' $OUTDIR/o989
rm -r -f sdir
