#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other3a ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -o ~hello.c > $OUTDIR/o837 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o837
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o837
cd ..
rm -r -f sdir
