#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov6 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN distclean > $OUTDIR/o44 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o44
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o44
cd ..
rm -r -f sdir
