#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-2a -n -w > $OUTDIR/o987 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o987
$INDIR/util/makeoutputcleanup $OUTDIR/o987
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o987

cat hello >> $OUTDIR/o987
cd ..
rm -r -f sdir
