#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc8 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --include-dir=./headers > $OUTDIR/o189 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o189
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o189
cd ..
rm -r -f sdir
