#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-2a -i -n -s > $OUTDIR/o959 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o959
$INDIR/util/makeoutputcleanup $OUTDIR/o959
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o959

cat hello >> $OUTDIR/o959
cd ..
rm -r -f sdir
