#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-2a -p -s -w > $OUTDIR/o1296 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1296
$INDIR/util/makeoutputcleanup $OUTDIR/o1296
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o1296

cat hello >> $OUTDIR/o1296
cd ..
rm -r -f sdir
