#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other2a ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/Makefile-cov5a > $OUTDIR/o978 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o978
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o978
cat hello >> $OUTDIR/o978
cd ..
rm -r -f sdir
