#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16h ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -p > $OUTDIR/o249 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o249
$INDIR/util/makeoutputcleanup $OUTDIR/o249
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o249

cat make >> $OUTDIR/o249
cd ..
rm -r -f sdir
