#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-2a -i -p -s -w > $OUTDIR/o129 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o129
$INDIR/util/makeoutputcleanup $OUTDIR/o129
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o129

cat hello >> $OUTDIR/o129
cd ..
rm -r -f sdir
