#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --new-file= > $OUTDIR/o965 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o965
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o965
cd ..
rm -r -f sdir
