#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --file $INDIR/n10test/makefile-3a --file $INDIR/n10test/makefile-3b > $OUTDIR/o1618 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1618
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1618
cat hello >> $OUTDIR/o1618
cd ..
rm -r -f sdir
