#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -k -p -s > $OUTDIR/o838 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o838
$INDIR/util/makeoutputcleanup $OUTDIR/o838
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o838

cat hello >> $OUTDIR/o838
cd ..
rm -r -f sdir
