#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov10 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN --keep-going > $OUTDIR/o783 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o783
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o783
cd ..
rm -r -f sdir
