#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
export HOMETEMP="$HOME"
export HOME=""
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1e > $OUTDIR/o4 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o4
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
sed -i -n '$d' $OUTDIR/o4
fi

cat hello >> $OUTDIR/o4
cd ..
rm -r -f sdir
export HOME="$HOMETEMP"
