#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -n -w > $OUTDIR/o704 2>&1
$INDIR/util/rm-makestuff -d $OUTDIR/o704
$INDIR/util/makeoutputcleanup $OUTDIR/o704
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o704

cat hello >> $OUTDIR/o704
cd ..
rm -r -f sdir
