#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other3 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -o ./hello.c > $OUTDIR/o412 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o412
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o412
cat hello >> $OUTDIR/o412
cd ..
rm -r -f sdir
