#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -i -s > $OUTDIR/o1392 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1392
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o1392
cat hello >> $OUTDIR/o1392
cd ..
rm -r -f sdir
