#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov3a ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/Makefile-cov3l -f $INDIR/n10test/Makefile-cov3ll > $OUTDIR/o404 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o404
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o404
cd ..
rm -r -f sdir
