#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-1a -n -p -s > $OUTDIR/o41 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o41
$INDIR/util/makeoutputcleanup $OUTDIR/o41
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi
sed -i -n '$d' $OUTDIR/o41

cat hello >> $OUTDIR/o41
cd ..
rm -r -f sdir
