#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-2a -i -s -w > $OUTDIR/o251 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o251
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

sed -i -n '$d' $OUTDIR/o251
cat hello >> $OUTDIR/o251
cd ..
rm -r -f sdir
