#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

function outputcheck() {
  r="$1"
  if grep -q -E "$r" $OUTDIR/o8; then
    echo 1 &>>$OUTDIR/o8
    return 1
  fi
    echo 0 &>>$OUTDIR/o8
    return 0
}

timeout ${TIMEOUT}s $BIN input1 input2 notexist  &>$OUTDIR/o8
retval=$?
outputcheck "invalid user"
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o8
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o8
else
    echo 0 &>>$OUTDIR/o8
fi
