#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

function outputcheck() {
  r="$1"
  if grep -q -E "$r" $OUTDIR/o7; then
    echo 1 &>>$OUTDIR/o7
    return 1
  fi
    echo 0 &>>$OUTDIR/o7
    return 0
}

timeout ${TIMEOUT}s $BIN  &>$OUTDIR/o7
retval=$?
outputcheck "missing operand"
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o7
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o7
else
    echo 0 &>>$OUTDIR/o7
fi
