#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

OPT=("-P")

function outputcheck() {
  r="$1"
  if grep -q -E "$r" $OUTDIR/o17; then
    echo 1 &>>$OUTDIR/o17
    return 1
  fi
    echo 0 &>>$OUTDIR/o17
    return 0
}
>$OUTDIR/o17
touch file
for opt in ${OPT[@]}; do
    timeout ${TIMEOUT}s $BIN $opt file &>>$OUTDIR/o17
    retval=$?
    outputcheck "missing operand after \`file'"
    if [[ $retval -eq 124 ]]; then
        echo 1 &>>$OUTDIR/o17
    elif [[ $retval -gt 128 ]]; then
        echo 1 &>>$OUTDIR/o17
    else
        echo 0 &>>$OUTDIR/o17
    fi
done
