#!/bin/bash

DEBOP_DIR=/usr/local/debop
DEBOP_BIN=${DEBOP_DIR}/build/bin/reducer
TIMEOUT=3600 #6h
iternum=100000000

realorcov=0 #1 means real, others mean cov
version=0

for samplenum in 10000
do
    for k in 50
    do
	for alpha in 0.5
	do
	    for beta in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
	    do
	        timeout -s 9 $TIMEOUT ./run_debop ${realorcov} ${samplenum} ${iternum} ${alpha} ${beta} $k ${version}
    	    done
	done
    done
done

