#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov3a ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/Makefile-cov3m > $OUTDIR/o957 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o957
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat make >> $OUTDIR/o957
cd ..
rm -r -f sdir
