#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -e -f $INDIR/n10test/makefile-1a -p > $OUTDIR/o645 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o645
$INDIR/util/makeoutputcleanup $OUTDIR/o645
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o645
cd ..
rm -r -f sdir
