#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc8 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -I./headers > $OUTDIR/o1110 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1110
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1110
cd ..
rm -r -f sdir
