#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -e -f $INDIR/n10test/makefile-2a -i -n -p -s > $OUTDIR/o1623 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1623
$INDIR/util/makeoutputcleanup $OUTDIR/o1623
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1623
cd ..
rm -r -f sdir
