#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov1 ./sdir
export MAKEFILE="$INDIR/n10test/makefile-cov1"
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $MAKEFILE > $OUTDIR/o1704 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o1704
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cd ..
rm -r -f sdir
