#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-other0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN > $OUTDIR/o258 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o258
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cd ..
rm -r -f sdir
