#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir0 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -i -p -s -w > $OUTDIR/o1610 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1610
$INDIR/util/makeoutputcleanup $OUTDIR/o1610
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1610
cd ..
rm -r -f sdir
