#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-cov16b ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -p > $OUTDIR/o1604 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1604
$INDIR/util/makeoutputcleanup $OUTDIR/o1604
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat make >> $OUTDIR/o1604
cd ..
rm -r -f sdir
