#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -d -f $INDIR/n10test/makefile-1a -k -n -p -w > $OUTDIR/o1767 2>&1
$INDIR/util/rm-makestuff -a $OUTDIR/o1767
$INDIR/util/makeoutputcleanup $OUTDIR/o1767
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1767
cd ..
rm -r -f sdir
