#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir-tc11 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -I ./headers1/headers2 > $OUTDIR/o394 2>&1
$INDIR/util/makeoutputcleanup $OUTDIR/o394
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o394
cd ..
rm -r -f sdir
