#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
CURRDIR=$(pwd)

cp -r -p $INDIR/n10test/sdir2 ./sdir
cd sdir
timeout -k 9 ${TIMEOUT}s $BIN -f $INDIR/n10test/makefile-1a -k -n -p > $OUTDIR/o1052 2>&1
$INDIR/util/rm-makestuff -p $OUTDIR/o1052
$INDIR/util/makeoutputcleanup $OUTDIR/o1052
if [ -f default.profraw ]; then
    mv default.profraw ${CURRDIR}/
fi

cat hello >> $OUTDIR/o1052
cd ..
rm -r -f sdir
