#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN -m 700 newdir &>$OUTDIR/o41

echo "$?" >>$OUTDIR/o41
info=`ls -ald newdir | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o41


