#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN -m 444 tech &>$OUTDIR/o48

echo "$?" >>$OUTDIR/o48
info=`ls -ald tech | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o48

