#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN test1 test2 test3 &>$OUTDIR/o21

echo "$?" >>$OUTDIR/o21
info=`ls -ald test1 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o21
info=`ls -ald test2 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o21
info=`ls -ald test3 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o21

