#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

touch file
timeout ${TIMEOUT}s $BIN  "-m" file  &>$OUTDIR/o14
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o14
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o14
else
    echo 0 &>>$OUTDIR/o14
fi