#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/tmp/test
timeout -k 9 ${TIMEOUT}s $BIN -p $(pwd)/tmp/test/test1/test2/test3/test4 &>$OUTDIR/o22

echo "$?" >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp/test | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp/test/test1 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp/test/test1/test2 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp/test/test1/test2/test3 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22
info=`ls -ald $(pwd)/tmp/test/test1/test2/test3/test4 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o22

rm -fr $(pwd)/tmp/test
