#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir $(pwd)/tmp
timeout -k 9 ${TIMEOUT}s $BIN -v $(pwd)/tmp/pkumar &>$OUTDIR/o33

echo "$?" >>$OUTDIR/o33
info=`ls -ald $(pwd)/tmp/pkumar | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o33

rm -fr $(pwd)/tmp/pkumar
