#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/linuxbuzz
timeout -k 9 ${TIMEOUT}s $BIN -Z $(pwd)/linuxbuzz &>$OUTDIR/o25

echo "$?" >>$OUTDIR/o25
info=`ls -ald $(pwd)/linuxbuzz | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o25
info=`ls -Zd $(pwd)/linuxbuzz`
echo ${info} >>$OUTDIR/o25

rm -fr $(pwd)/linuxbuzz
