#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/debop_script/mkdir/tmp/customer

timeout -k 9 ${TIMEOUT}s $BIN -p $(pwd)/debop_script/mkdir/tmp/customer/acme/foo/bar &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/customer | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o46
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/customer/acme | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o46
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/customer/acme/foo | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o46
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/customer/acme/foo/bar | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o46

rm -fr $(pwd)/debop_script/mkdir/tmp/customer
