#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN -m 700 $(pwd)/shared &>$OUTDIR/o32

echo "$?" >>$OUTDIR/o32
info=`ls -ald $(pwd)/shared | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o32

rm -fr $(pwd)/shared

