#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir newdir

timeout -k 9 ${TIMEOUT}s $BIN newdir &>$OUTDIR/o40

echo "$?" >>$OUTDIR/o40
info=`ls -ald newdir | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o40


