#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/tmp
timeout -k 9 ${TIMEOUT}s $BIN -p $(pwd)/tmp/lab01/{expr1,expr2} $(pwd)/tmp/lab02/{expr3,expr4} &>$OUTDIR/o31

echo "$?" >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab01 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab01/expr1 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab01/expr2 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab02 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab02/expr3 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31
info=`ls -ald $(pwd)/tmp/lab02/expr4 | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o31

rm -fr $(pwd)/tmp/lab01 $(pwd)/tmp/lab02

