#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN mydir &>$OUTDIR/o19

echo "$?" >>$OUTDIR/o19
info=`ls -ald mydir | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o19

