#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/tmp
timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/tmp/newdir &>$OUTDIR/o36

echo "$?" >>$OUTDIR/o36
info=`ls -ald $(pwd)/tmp/newdir | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o36

rm -fr $(pwd)/tmp/newdir
