#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN  &>$OUTDIR/o13
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o13
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o13
else
    echo 0 &>>$OUTDIR/o13
fi