#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/debop_script/mkdir/tmp/linuxize
timeout -k 9 ${TIMEOUT}s $BIN -p $(pwd)/debop_script/mkdir/tmp/linuxize/Music/Rock/Gothic &>$OUTDIR/o39

echo "$?" >>$OUTDIR/o39
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/linuxize | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o39
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/linuxize/Music | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o39
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/linuxize/Music/Rock | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o39
info=`ls -ald $(pwd)/debop_script/mkdir/tmp/linuxize/Music/Rock/Gothic | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o39

rm -fr $(pwd)/debop_script/mkdir/tmp/linuxize
