#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir $(pwd)/root
timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/root/newdir &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
info=`ls -ald $(pwd)/root/newdir | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o37

