#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/backup &>$OUTDIR/o24

echo "$?" >>$OUTDIR/o24
info=`ls -ald $(pwd)/backup | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o24

rm -fr $(pwd)/backup
