#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

#should fail
timeout ${TIMEOUT}s $BIN '-m' 'd1/d2'  &>$OUTDIR/o11
echo "$?" >>$OUTDIR/o11

#ls -ld d1 | cut -d ' ' -f 2,3 &>>$OUTDIR/o11
#ls -ld d1/d2 | cut -d ' ' -f 2,3 &>>$OUTDIR/o11
