#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

timeout -k 9 ${TIMEOUT}s $BIN memos letters e-mail &>$OUTDIR/o45

echo "$?" >>$OUTDIR/o45
info=`ls -ald memos | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o45
info=`ls -ald letters | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o45
info=`ls -ald e-mail | tr -s ' ' | cut -d ' ' -f 1,2,3,4`
echo ${info} >>$OUTDIR/o45

