#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/dir0 ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "find ./dir0 -name '*.c' ! -type d -exec $BIN -H 'hello' '{}' +" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o48
echo "$?" >>$OUTDIR/o48

rm run.sh
