#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/* ./
mv dir1 .git

timeout -k 9 ${TIMEOUT}s $BIN -r --exclude-dir='.git' "hello" . &>$OUTDIR/o30
echo "$?" >>$OUTDIR/o30

rm -fr .git
