#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/dir2 ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "find . -name \"*.java\" -print0 | xargs -0 $BIN -i \".*Legacy.*xml\"" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o31
echo "$?" >>$OUTDIR/o31

rm run.sh
