#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
currdir=$(pwd)

touch file1
ln -s file1 sysfile1

{ timeout ${TIMEOUT}s $BIN -h $(whoami):sudo sysfile1; }  &>$OUTDIR/o5
ls -al sysfile1 | cut -d ' ' -f 4 &>>$OUTDIR/o5

{ timeout ${TIMEOUT}s $BIN -h $(whoami):$(whoami) sysfile1; } &>>$OUTDIR/o5
ls -al sysfile1 | cut -d ' ' -f 4 &>>$OUTDIR/o5
