#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN --iso=ns -d "1969-12-31 13:00:00.000000.2-1100"  &>$OUTDIR/o69
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o69
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o69
else
    echo 0 &>>$OUTDIR/o69
fi