#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN --iso=ns -d "2038-01-19 03:14:07.999999999"  &>$OUTDIR/o71
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o71
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o71
else
    echo 0 &>>$OUTDIR/o71
fi