#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN +%8:z  &>$OUTDIR/o77
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o77
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o77
else
    echo 0 &>>$OUTDIR/o77
fi
