#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN -I -d '2006-04-23 21 days ago'  &>$OUTDIR/o65
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o65
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o65
else
    echo 0 &>>$OUTDIR/o65
fi