#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN --iso -d May-23-2003  &>$OUTDIR/o66
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o66
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o66
else
    echo 0 &>>$OUTDIR/o66
fi