#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN --iso=sec -d @31536000  &>$OUTDIR/o67
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o67
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o67
else
    echo 0 &>>$OUTDIR/o67
fi