#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN --iso=ns -d'1970-01-01 00:00:00.2234567 UTC +961062237.987654321 sec'  &>$OUTDIR/o79
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o79
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o79
else
    echo 0 &>>$OUTDIR/o79
fi
