#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN +%::z  &>$OUTDIR/o74
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o74
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o74
else
    echo 0 &>>$OUTDIR/o74
fi