#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4


timeout ${TIMEOUT}s $BIN +%:8z  &>$OUTDIR/o78
retval=$?
if [[ $retval -eq 124 ]]; then
    echo 1 &>>$OUTDIR/o78
elif [[ $retval -gt 128 ]]; then
    echo 1 &>>$OUTDIR/o78
else
    echo 0 &>>$OUTDIR/o78
fi
