#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/myfile.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -I *" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o20

echo "$?" >>$OUTDIR/o20
test -f myfile.txt
echo "$?" >>$OUTDIR/o20

rm run.sh
