#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/linuxstufff.log ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -i linuxstufff.log" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o25

echo "$?" >>$OUTDIR/o25
test -f linuxstufff.log
echo "$?" >>$OUTDIR/o25

rm run.sh
