#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/mydirectory ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r mydirectory; } &>$OUTDIR/o21

echo "$?" >>$OUTDIR/o21
test -d mydirectory
echo "$?" >>$OUTDIR/o21
test -f mydirectory/file
echo "$?" >>$OUTDIR/o21
