#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/-file.txt ./
mkdir -p ./home/hope/
mv ./-file.txt ./home/hope/

{ timeout -k 9 ${TIMEOUT}s $BIN ./home/hope/-file.txt; } &>$OUTDIR/o13

echo "$?" >>$OUTDIR/o13
test -f ./home/hope/-file.txt
echo "$?" >>$OUTDIR/o13
