#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/unicron.txt ./

#write-protected file
echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN unicron.txt" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58
test -f unicron.txt
echo "$?" >>$OUTDIR/o58

rm run.sh
