#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/dir1 ./
cp -r $INDIR/I9/dir2 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r dir1 dir2; } &>$OUTDIR/o82

echo "$?" >>$OUTDIR/o82
test -d dir1
echo "$?" >>$OUTDIR/o82
test -f dir1/file
echo "$?" >>$OUTDIR/o82
test -d dir2
echo "$?" >>$OUTDIR/o82
test -f dir2/file
echo "$?" >>$OUTDIR/o82


