#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/linuxstufff.log ./

{ timeout -k 9 ${TIMEOUT}s $BIN linuxstufff.log; } &>$OUTDIR/o23

echo "$?" >>$OUTDIR/o23
test -f linuxstufff.log
echo "$?" >>$OUTDIR/o23


