#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I6/mydirectory ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r mydirectory; } &>$OUTDIR/o66

echo "$?" >>$OUTDIR/o66
test -d mydirectory
echo "$?" >>$OUTDIR/o66
test -f mydirectory/file.txt
echo "$?" >>$OUTDIR/o66
