#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/dir1 ./
rm dir1/file1

{ timeout -k 9 ${TIMEOUT}s $BIN -d dir1; } &>$OUTDIR/o72

echo "$?" >>$OUTDIR/o72
test -d dir1
echo "$?" >>$OUTDIR/o72


