#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/test1 ./
cp $INDIR/I8/test2 ./
cp $INDIR/I8/test3 ./
cp $INDIR/I8/test4 ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -Iv test*" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o77

echo "$?" >>$OUTDIR/o77
test -f test1
echo "$?" >>$OUTDIR/o77
test -f test2
echo "$?" >>$OUTDIR/o77
test -f test3
echo "$?" >>$OUTDIR/o77
test -f test4
echo "$?" >>$OUTDIR/o77

rm run.sh
