#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I0/-file.txt ./

#Intended failure
{ timeout -k 9 ${TIMEOUT}s $BIN -file.txt; } &>$OUTDIR/o8

echo "$?" >>$OUTDIR/o8
test -f -file.txt
echo "$?" >>$OUTDIR/o8

