#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/unicron.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f unicron.txt; } &>$OUTDIR/o59

echo "$?" >>$OUTDIR/o59
test -f unicron.txt
echo "$?" >>$OUTDIR/o59


