#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/megatron.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -i megatron.txt" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o56

echo "$?" >>$OUTDIR/o56
test -f megatron.txt
echo "$?" >>$OUTDIR/o56

rm run.sh
