#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/try2 ./
cp $INDIR/I7/try3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN *; } &>$OUTDIR/o70

echo "$?" >>$OUTDIR/o70
test -f try2
echo "$?" >>$OUTDIR/o70
test -f try3
echo "$?" >>$OUTDIR/o70


