#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/*.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN *; } &>$OUTDIR/o62

echo "$?" >>$OUTDIR/o62
test -f myfile.txt
echo "$?" >>$OUTDIR/o62
test -f file.txt
echo "$?" >>$OUTDIR/o62


