#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/Pictures ./

{ timeout -k 9 ${TIMEOUT}s $BIN Pictures/529395.jpg; } &>$OUTDIR/o74

echo "$?" >>$OUTDIR/o74
test -f Pictures/529395.jpg
echo "$?" >>$OUTDIR/o74


