#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f myfile.txt; } &>$OUTDIR/o16

echo "$?" >>$OUTDIR/o16
test -f myfile.txt
echo "$?" >>$OUTDIR/o16
