#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/file1 ./
cp $INDIR/I3/file2 ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -i file1 file2" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
test -f file1
echo "$?" >>$OUTDIR/o46
test -f file2
echo "$?" >>$OUTDIR/o46

rm run.sh
