#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/myfile ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -i myfile" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o83

echo "$?" >>$OUTDIR/o83
test -f myfile
echo "$?" >>$OUTDIR/o83

rm run.sh
