#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I6/mydirectory ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf mydirectory; } &>$OUTDIR/o67

echo "$?" >>$OUTDIR/o67
test -d mydirectory
echo "$?" >>$OUTDIR/o67
test -f mydirectory/file.txt
echo "$?" >>$OUTDIR/o67
