#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/* ./
rm -f tech.txt #Remove the write-protected one

{ timeout -k 9 ${TIMEOUT}s $BIN -f *.txt; } &>$OUTDIR/o35

echo "$?" >>$OUTDIR/o35
test -f file1.txt
echo "$?" >>$OUTDIR/o35
test -f file2.txt
echo "$?" >>$OUTDIR/o35
test -f file3.txt
echo "$?" >>$OUTDIR/o35
test -f file4.txt
echo "$?" >>$OUTDIR/o35


