#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/hello.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -iv hello.txt" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o76

echo "$?" >>$OUTDIR/o76
test -f hello.txt
echo "$?" >>$OUTDIR/o76

rm run.sh
