#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/dbstore ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r dbstore/; } &>$OUTDIR/o27

echo "$?" >>$OUTDIR/o27
test -d dbstore
echo "$?" >>$OUTDIR/o27
test -f dbstore/file1.log
echo "$?" >>$OUTDIR/o27
test -f dbstore/file2.log
echo "$?" >>$OUTDIR/o27
test -f dbstore/file3.log
echo "$?" >>$OUTDIR/o27
test -f dbstore/service
echo "$?" >>$OUTDIR/o27
