#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/decepticons ./

{ timeout -k 9 ${TIMEOUT}s $BIN decepticons; } &>$OUTDIR/o54

echo "$?" >>$OUTDIR/o54
test -d decepticons
echo "$?" >>$OUTDIR/o54
test -f decepticons/shockwave.txt
echo "$?" >>$OUTDIR/o54
test -f decepticons/soundwave.txt
echo "$?" >>$OUTDIR/o54
test -f decepticons/starscream.txt
echo "$?" >>$OUTDIR/o54
