#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/cases ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r cases; } &>$OUTDIR/o50

echo "$?" >>$OUTDIR/o50
test -d cases
echo "$?" >>$OUTDIR/o50
test -f cases/file
echo "$?" >>$OUTDIR/o50


