#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/-store ./

#Intended failure
{ timeout -k 9 ${TIMEOUT}s $BIN -store; } &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
test -f -store
echo "$?" >>$OUTDIR/o37


