#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file*.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1.txt file2.txt file3.txt file4.txt; } &>$OUTDIR/o24

echo "$?" >>$OUTDIR/o24
test -f file1.txt
echo "$?" >>$OUTDIR/o24
test -f file2.txt
echo "$?" >>$OUTDIR/o24
test -f file3.txt
echo "$?" >>$OUTDIR/o24
test -f file4.txt
echo "$?" >>$OUTDIR/o24


