#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/tech.txt ./

#tech.txt is write-protected
echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN tech.txt" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o29

echo "$?" >>$OUTDIR/o29
test -f tech.txt
echo "$?" >>$OUTDIR/o29

rm run.sh
