#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/files ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rfv files/; } &>$OUTDIR/o79

echo "$?" >>$OUTDIR/o79
test -d files
echo "$?" >>$OUTDIR/o79
test -d files/a-test
echo "$?" >>$OUTDIR/o79
test -d files/b-test
echo "$?" >>$OUTDIR/o79
test -d files/c-test
echo "$?" >>$OUTDIR/o79

for i in a b c; do
    for j in 1 2 3; do
	test -f files/${i}-test-${j}
	echo "$?" >>$OUTDIR/o79
    done
done


