#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

#Permission denied
{ timeout -k 9 ${TIMEOUT}s $BIN -f /mytest/myfile; } &>$OUTDIR/o32

echo "$?" >>$OUTDIR/o32
test -f /mytest/myfile
echo "$?" >>$OUTDIR/o32
