#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN myfile.txt; } &>$OUTDIR/o36

echo "$?" >>$OUTDIR/o36
test -f myfile.txt
echo "$?" >>$OUTDIR/o36
bzip2 -d <myfile.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o36

