#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/linux-3.18.19.tar ./
bzip2 linux-3.18.19.tar

{ timeout -k 9 ${TIMEOUT}s $BIN -tv linux-3.18.19.tar.bz2; } &>$OUTDIR/o22

echo "$?" >>$OUTDIR/o22
test -f linux-3.18.19.tar.bz2
echo "$?" >>$OUTDIR/o22

bzip2 -d linux-3.18.19.tar.bz2
diff linux-3.18.19.tar $INDIR/I2/linux-3.18.19.tar
echo "$?" &>>$OUTDIR/o22

