#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file1.txt ./
cp $INDIR/I2/file2.txt ./
cp $INDIR/I2/file3.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1.txt file2.txt file3.txt; } &>$OUTDIR/o11

echo "$?" >>$OUTDIR/o11
test -f file1.txt
echo "$?" >>$OUTDIR/o11
test -f file2.txt
echo "$?" >>$OUTDIR/o11
test -f file3.txt
echo "$?" >>$OUTDIR/o11

bzip2 -d <file1.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o11
bzip2 -d <file2.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o11
bzip2 -d <file3.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o11

