#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/input.txt ./
bzip2 input.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d input.txt.bz2; } &>$OUTDIR/o7

echo "$?" >>$OUTDIR/o7
test -f input.txt.bz2
echo "$?" >>$OUTDIR/o7
cat input.txt &>>$OUTDIR/o7

