#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/filename ./

{ timeout -k 9 ${TIMEOUT}s $BIN -zk filename; } &>$OUTDIR/o27

echo "$?" >>$OUTDIR/o27
test -f filename
echo "$?" >>$OUTDIR/o27
bzip2 -d <filename.bz2 >rslt
cat rslt >>$OUTDIR/o27

