#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file.txt ./
bzip2 file.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d file.txt.bz2; } &>$OUTDIR/o17

echo "$?" >>$OUTDIR/o17
test -f file.txt.bz2
echo "$?" >>$OUTDIR/o17
cat file.txt &>>$OUTDIR/o17

