#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f myfile.txt; } &>$OUTDIR/o43

echo "$?" >>$OUTDIR/o43
test -f myfile.txt
echo "$?" >>$OUTDIR/o43
bzip2 -d <myfile.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o43
