#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

touch myfile.txt.bz2
>$OUTDIR/o41
{ timeout -k 9 ${TIMEOUT}s $BIN -t myfile.txt.bz2; } #&>$OUTDIR/o41

echo "$?" >>$OUTDIR/o41
test -f myfile.txt.bz2
echo "$?" >>$OUTDIR/o41

