#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/input.txt ./
bzip2 input.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -t input.txt.bz2; } &>$OUTDIR/o8

echo "$?" >>$OUTDIR/o8
test -f input.txt.bz2
echo "$?" >>$OUTDIR/o8

