#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 myfile.txt; } &>$OUTDIR/o45

echo "$?" >>$OUTDIR/o45
test -f myfile.txt
echo "$?" >>$OUTDIR/o45
bzip2 -d <myfile.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o45
