#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/file1 ./
cp $INDIR/I8/file2 ./
cp $INDIR/I8/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1 file2 file3; } &>$OUTDIR/o51

echo "$?" >>$OUTDIR/o51
test -f file1
echo "$?" >>$OUTDIR/o51
test -f file2
echo "$?" >>$OUTDIR/o51
test -f file3
echo "$?" >>$OUTDIR/o51

bzip2 -d <file1.bz2 >rslt
cat rslt &>>$OUTDIR/o51
bzip2 -d <file2.bz2 >rslt
cat rslt &>>$OUTDIR/o51
bzip2 -d <file3.bz2 >rslt
cat rslt &>>$OUTDIR/o51

