#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file_a ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v file_a; } &>$OUTDIR/o57

echo "$?" >>$OUTDIR/o57
test -f file_a
echo "$?" >>$OUTDIR/o57
bzip2 -d <file_a.bz2 >rslt
cat rslt &>>$OUTDIR/o57


