#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/infile ./

{ timeout -k 9 ${TIMEOUT}s $BIN infile; } &>$OUTDIR/o46

echo "$?" >>$OUTDIR/o46
test -f infile
echo "$?" >>$OUTDIR/o46
bzip2 -d <infile.bz2 >rslt
cat rslt &>>$OUTDIR/o46

