#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/filename ./
bzip2 filename

{ timeout -k 9 ${TIMEOUT}s $BIN -d filename.bz2; } &>$OUTDIR/o32

echo "$?" >>$OUTDIR/o32
test -f filename.bz2
echo "$?" >>$OUTDIR/o32
cat filename &>>$OUTDIR/o32

