#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file_a ./

{ timeout -k 9 ${TIMEOUT}s $BIN -k file_a; } &>$OUTDIR/o58

echo "$?" >>$OUTDIR/o58
test -f file_a
echo "$?" >>$OUTDIR/o58
bzip2 -d <file_a.bz2 >rslt
cat rslt &>>$OUTDIR/o58


