#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -c file.txt >file.txt.bz2; } &>$OUTDIR/o15

echo "$?" >>$OUTDIR/o15
test -f file.txt
echo "$?" >>$OUTDIR/o15

rm *.txt
bzip2 -d <file.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o15

