#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/test.dat ./

{ timeout -k 9 ${TIMEOUT}s $BIN test.dat; } &>$OUTDIR/o49

echo "$?" >>$OUTDIR/o49
test -f test.dat
echo "$?" >>$OUTDIR/o49
bzip2 -d <test.dat.bz2 >rslt
cat rslt &>>$OUTDIR/o49

