#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -k file.txt; } &>$OUTDIR/o16

echo "$?" >>$OUTDIR/o16
test -f file.txt
echo "$?" >>$OUTDIR/o16
bzip2 -d <file.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o16

