#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/backup.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -zk backup.tar; } &>$OUTDIR/o28

echo "$?" >>$OUTDIR/o28
test -f backup.tar
echo "$?" >>$OUTDIR/o28
rm backup.tar
bzip2 -d backup.tar.bz2
diff backup.tar $INDIR/I3/backup.tar >/dev/null
echo "$?" >>$OUTDIR/o28

