#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file_a ./
bzip2 file_a

{ timeout -k 9 ${TIMEOUT}s $BIN -d file_a.bz2; } &>$OUTDIR/o56

echo "$?" >>$OUTDIR/o56
test -f file_a.bz2
echo "$?" >>$OUTDIR/o56
cat file_a &>>$OUTDIR/o56


