#!/bin/bash 

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -vv file.txt; } &>$OUTDIR/o13

echo "$?" >>$OUTDIR/o13
test -f file.txt
echo "$?" >>$OUTDIR/o13

