#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file1.txt ./
cp $INDIR/I2/file2.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -c file1.txt >file.bz2; } &>$OUTDIR/o14
{ timeout -k 9 ${TIMEOUT}s $BIN -c file2.txt >>file.bz2; } &>>$OUTDIR/o14

echo "$?" >>$OUTDIR/o14
test -f file1.txt
echo "$?" >>$OUTDIR/o14
test -f file2.txt
echo "$?" >>$OUTDIR/o14
bzip2 -d <file.bz2 >rslt
cat rslt >>$OUTDIR/o14

