#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/filename ./

{ timeout -k 9 ${TIMEOUT}s $BIN -z filename; } &>$OUTDIR/o24

echo "$?" >>$OUTDIR/o24
test -f filename
echo "$?" >>$OUTDIR/o24
bzip2 -d <filename.bz2 >rslt
cat rslt &>>$OUTDIR/o24

