#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/infile ./

{ timeout -k 9 ${TIMEOUT}s $BIN -9 infile; } &>$OUTDIR/o47

echo "$?" >>$OUTDIR/o47
test -f infile
echo "$?" >>$OUTDIR/o47
bzip2 -d <infile.bz2 >rslt
cat rslt &>>$OUTDIR/o47

