#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/Etcher-linux-x64.AppImage ./
bzip2 Etcher-linux-x64.AppImage

{ timeout -k 9 ${TIMEOUT}s $BIN -vd Etcher-linux-x64.AppImage.bz2; } &>$OUTDIR/o33

echo "$?" >>$OUTDIR/o33
test -f Etcher-linux-x64.AppImage.bz2
echo "$?" >>$OUTDIR/o33
cat Etcher-linux-x64.AppImage &>>$OUTDIR/o33

