#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/file.txt ./
bzip2 file.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -c file.txt.bz2 >file.txt; } &>$OUTDIR/o18

echo "$?" >>$OUTDIR/o18
test -f file.txt.bz2
echo "$?" >>$OUTDIR/o18
cat file.txt &>>$OUTDIR/o18

