#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/myfile.txt ./
bzip2 myfile.txt

{ timeout -k 9 ${TIMEOUT}s $BIN -d myfile.txt.bz2; } &>$OUTDIR/o42

echo "$?" >>$OUTDIR/o42
test -f myfile.txt.bz2
echo "$?" >>$OUTDIR/o42
cat myfile.txt >>$OUTDIR/o42
