#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/backup.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -z backup.tar; } &>$OUTDIR/o26

echo "$?" >>$OUTDIR/o26
test -f backup.tar
echo "$?" >>$OUTDIR/o26
bzip2 -d backup.tar.bz2
diff backup.tar $INDIR/I3/backup.tar >/dev/null
echo "$?" >>$OUTDIR/o26

