#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/Etcher-linux-x64.AppImage ./

{ timeout -k 9 ${TIMEOUT}s $BIN -k1 Etcher-linux-x64.AppImage; } &>$OUTDIR/o29

echo "$?" >>$OUTDIR/o29
test -f Etcher-linux-x64.AppImage
echo "$?" >>$OUTDIR/o29
bzip2 -d <Etcher-linux-x64.AppImage.bz2 >rslt
cat rslt >>$OUTDIR/o29

