#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/filename ./

{ timeout -k 9 ${TIMEOUT}s $BIN filename; } &>$OUTDIR/o34

echo "$?" >>$OUTDIR/o34
test -f filename
echo "$?" >>$OUTDIR/o34
bzip2 -d <filename.bz2 >rslt
cat rslt &>>$OUTDIR/o34

