#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/filename ./
bzip2 filename

{ timeout -k 9 ${TIMEOUT}s $BIN -d filename.bz2; } &>$OUTDIR/o35

echo "$?" >>$OUTDIR/o35
test -f filename.bz2
echo "$?" >>$OUTDIR/o35
cat filename &>>$OUTDIR/o35