#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/input.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -k input.txt; } &>$OUTDIR/o6

echo "$?" >>$OUTDIR/o6
test -f input.txt
echo "$?" >>$OUTDIR/o6
bzip2 -d <input.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o6

