#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/file7.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN file7.tar; } &>$OUTDIR/o53

echo "$?" >>$OUTDIR/o53
test -f file7.tar
echo "$?" >>$OUTDIR/o53

if [ -f file7.tar ]; then
    rm file7.tar #In case the file still exists
fi
bzip2 -d file7.tar.bz2
diff file7.tar $INDIR/I8/file7.tar >/dev/null
echo "$?" >>$OUTDIR/o53

