#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -c myfile.txt > myfile.txt.bz2; } &>$OUTDIR/o37

echo "$?" >>$OUTDIR/o37
test -f myfile.txt
echo "$?" >>$OUTDIR/o37
bzip2 -d <myfile.txt.bz2 >rslt
cat rslt &>>$OUTDIR/o37

