#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I6/infile ./
bzip2 infile

{ timeout -k 9 ${TIMEOUT}s $BIN -d infile.bz2; } &>$OUTDIR/o48

echo "$?" >>$OUTDIR/o48
test -f infile.bz2
echo "$?" >>$OUTDIR/o48
cat infile &>>$OUTDIR/o48

