#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/pattern.txt ./
cp $INDIR/I5/geekfile.txt ./

timeout -k 9 ${TIMEOUT}s $BIN -f pattern.txt geekfile.txt &>$OUTDIR/o78
echo "$?" >>$OUTDIR/o78

