#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/dir0/* ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "find . -name \"*.mp3\" | $BIN -i JayZ | grep -vi \"remix\"" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o34
echo "$?" >>$OUTDIR/o34

rm run.sh
