#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/geekfile.txt ./

timeout -k 9 ${TIMEOUT}s $BIN –e "Agarwal" –e "Aggarwal" –e "Agrawal" geekfile.txt &>$OUTDIR/o77
echo "$?" >>$OUTDIR/o77

