#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/etcmotd ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "cat /etc/passwd | $BIN 'qxin6' - etcmotd" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o61
echo "$?" >>$OUTDIR/o61

rm run.sh
