#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I6/c*.* ./

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname} c*.*; } &>$OUTDIR/o66

echo "$?" >>$OUTDIR/o66
own0=`ls -al c*.* | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al c*.* | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o66

#parentI62