#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I8/file1 ./

{ timeout -k 9 ${TIMEOUT}s $BIN ${uid}:${uid} file1; } &>$OUTDIR/o88

echo "$?" >>$OUTDIR/o88
own0=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o88


#parentI810