#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)
uid=`id -u ${uname}`

cp $INDIR/I2/file1 ./
ln -s file1 symfile1

{ timeout -k 9 ${TIMEOUT}s $BIN -h ${uname} symfile1; } &>$OUTDIR/o18

echo "$?" >>$OUTDIR/o18
own0=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al file1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o18

own0=`ls -al symfile1 | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al symfile1 | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o18


#parentI27