#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

uname=$(whoami)

cp $INDIR/I6/caps.c ./

{ timeout -k 9 ${TIMEOUT}s $BIN ${uname}: caps.c; } &>$OUTDIR/o70

echo "$?" >>$OUTDIR/o70
own0=`ls -al caps.c | tr -s ' ' | cut -d ' ' -f 3`
own1=`ls -al caps.c | tr -s ' ' | cut -d ' ' -f 4`
echo "${own0} ${own1}" >>$OUTDIR/o70

#parentI66