#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/sort1.txt ./
cp $INDIR/I7/sort2.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN sort1.txt sort2.txt; } &>$OUTDIR/o91

echo "$?" >>$OUTDIR/o91


