#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/etc_passwd.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "$BIN -t ':' -k 7 etc_passwd.txt | head" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o72

echo "$?" >>$OUTDIR/o72

rm run.sh
