#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/du_hs_usr_share.txt ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "cat du_hs_usr_share.txt | $BIN -nr" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o68

echo "$?" >>$OUTDIR/o68

rm run.sh


