#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/perfect.txt ./
cp $INDIR/I2/perfect2.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -m perfect.txt perfect2.txt; } &>$OUTDIR/o43

echo "$?" >>$OUTDIR/o43
