#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -o output.txt file.txt; } &>$OUTDIR/o13

echo "$?" >>$OUTDIR/o13
cat output.txt >>$OUTDIR/o13


