#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file2 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file2 -n >file2_sorted.txt; } &>$OUTDIR/o110

echo "$?" >>$OUTDIR/o110
cat file2_sorted.txt >>$OUTDIR/o110

