#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/subdir1 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptr1.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN -r $(pwd)/testdir/subdir1  > $OUTDIR/o52 2>&1 | tee -a $OUTDIR/o52

$INDIR/util/cpoptr1.sh $INDIR $OUTDIR/o52
