#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file3 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptf.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file3 -f  > $OUTDIR/o135 2>&1 | tee -a $OUTDIR/o135

$INDIR/util/cpoptf.sh $(pwd) $OUTDIR/o135
