#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file9 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptd.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file9.z -d  > $OUTDIR/o204 2>&1 | tee -a $OUTDIR/o204

$INDIR/util/cpoptd.sh $(pwd) $OUTDIR/o204
