#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file16 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpopt3.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file16 -3  > $OUTDIR/o42 2>&1 | tee -a $OUTDIR/o42

$INDIR/util/cpopt3.sh $(pwd) $OUTDIR/o42