#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/subdir3 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptr2.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN --recursive $(pwd)/testdir/subdir3  > $OUTDIR/o64 2>&1 | tee -a $OUTDIR/o64

$INDIR/util/cpoptr2.sh $(pwd) $OUTDIR/o64
