#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp $INDIR/testdir/file1 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/longfilename.sh $(pwd)/util/
cp -r $INDIR/util/cplongname.sh $(pwd)/util/
mkdir $(pwd)/length

cp -r $INDIR/length/abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcde $(pwd)/
$INDIR/util/longfilename.sh $(pwd)/length/ $OUTDIR/o206

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/length/abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcde  > $OUTDIR/o206 2>&1 | tee -a $OUTDIR/o206

$INDIR/util/cplongname.sh $(pwd) $OUTDIR/o206
