#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file20 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpopt7.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file20 -7  > $OUTDIR/o92 2>&1 | tee -a $OUTDIR/o92

$INDIR/util/cpopt7.sh $(pwd) $OUTDIR/o92
