#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/binaryfile1 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/breakscript.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/binaryfile1  > $OUTDIR/o164 2>&1 | tee -a $OUTDIR/o164

$INDIR/util/breakscript.sh $(pwd) $OUTDIR/o164 >>$OUTDIR/o164
