#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file18 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpopt5.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file18 -5  > $OUTDIR/o143 2>&1 | tee -a $OUTDIR/o143

$INDIR/util/cpopt5.sh $(pwd) $OUTDIR/o143
