#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file11 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptv.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file11 -v  > $OUTDIR/o37 2>&1 | tee -a $OUTDIR/o37

$INDIR/util/cpoptv.sh $(pwd) $OUTDIR/o37
