#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file13 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpoptr.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/subdir2 -r  > $OUTDIR/o68 2>&1 | tee -a $OUTDIR/o68

$INDIR/util/cpoptr.sh $(pwd) $OUTDIR/o68
