#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir $(pwd)/testdir
cp -r $INDIR/testdir/file19 $(pwd)/testdir/
mkdir $(pwd)/util
cp -r $INDIR/util/cpopt6.sh $(pwd)/util/

timeout -k 9 ${TIMEOUT}s $BIN $(pwd)/testdir/file19 -6  > $OUTDIR/o18 2>&1 | tee -a $OUTDIR/o18

$INDIR/util/cpopt6.sh $(pwd) $OUTDIR/o18
