#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4 #NOTE: this should be passed as a COPIED version
CURRDIR=$(pwd)

#Clean
if [ ! -d $OUTDIR ]; then
    mkdir -p $OUTDIR
else
    rm -fr $OUTDIR/*
fi

#Use a tmp directory for execution
if [ ! -d $CURRDIR/tmp ]; then
    mkdir $CURRDIR/tmp
else
    chmod 755 -R $CURRDIR/tmp
    rm -fr $CURRDIR/tmp/*
fi
cd $CURRDIR/tmp

#Execute with every test
for testf in $CURRDIR/testscript/kn/*
do
    timeout ${TIMEOUT}s ${testf} $BIN $OUTDIR $TIMEOUT $INDIR
    chmod 755 -R $CURRDIR/tmp
    rm -fr $CURRDIR/tmp/*
done
