#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "sort $INDIR/I9/file.txt | $BIN" >>run.sh
chmod 700 run.sh

timeout -k 9 ${TIMEOUT}s ./run.sh &>$OUTDIR/o70

echo "$?" >>$OUTDIR/o70

