#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test ./
cp -r $INDIR/I8/test1 ./
cp -r $INDIR/I8/test2 ./
cp -r $INDIR/I8/test3 ./
cp -r $INDIR/I8/test4 ./
cp -r $INDIR/I8/testdir ./

{ timeout -k 9 ${TIMEOUT}s $BIN --create -f test.tar test*; } &>$OUTDIR/o61

echo "$?" >>$OUTDIR/o61
rm -fr test test1 test2 test3 test4 testdir
tar xf test.tar
diff test $INDIR/I8/test >/dev/null
echo "$?" >>$OUTDIR/o61
diff test1 $INDIR/I8/test1 >/dev/null
echo "$?" >>$OUTDIR/o61
diff test2 $INDIR/I8/test2 >/dev/null
echo "$?" >>$OUTDIR/o61
diff test3 $INDIR/I8/test3 >/dev/null
echo "$?" >>$OUTDIR/o61
diff test4 $INDIR/I8/test4 >/dev/null
echo "$?" >>$OUTDIR/o61

diff testdir/test $INDIR/I8/testdir/test >/dev/null
echo "$?" >>$OUTDIR/o61
diff testdir/test1 $INDIR/I8/testdir/test1 >/dev/null
echo "$?" >>$OUTDIR/o61
diff testdir/test2 $INDIR/I8/testdir/test2 >/dev/null
echo "$?" >>$OUTDIR/o61
diff testdir/test3 $INDIR/I8/testdir/test3 >/dev/null
echo "$?" >>$OUTDIR/o61
diff testdir/test4 $INDIR/I8/testdir/test4 >/dev/null
echo "$?" >>$OUTDIR/o61


#I8