#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/file1 ./
cp -r $INDIR/I9/file2 ./
cp -r $INDIR/I9/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cf file.tar file1 file2 file3; } &>$OUTDIR/o76

echo "$?" >>$OUTDIR/o76
rm file1 file2 file3
tar xf file.tar
diff file1 $INDIR/I9/file1 >/dev/null
echo "$?" >>$OUTDIR/o76
diff file2 $INDIR/I9/file2 >/dev/null
echo "$?" >>$OUTDIR/o76
diff file3 $INDIR/I9/file3 >/dev/null
echo "$?" >>$OUTDIR/o76

#I9