#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I0/Phpfiles-org.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf Phpfiles-org.tar --wildcards '*.php'; } &>$OUTDIR/o7

echo "$?" >>$OUTDIR/o7

diff php/iframe_ew.php $INDIR/I0/php/iframe_ew.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/videos_all.php $INDIR/I0/php/videos_all.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/rss.php $INDIR/I0/php/rss.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/index.php $INDIR/I0/php/index.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/vendor.php $INDIR/I0/php/vendor.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/video_title.php $INDIR/I0/php/video_title.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/report.php $INDIR/I0/php/report.php >/dev/null
echo "$?" >>$OUTDIR/o7

diff php/video.php $INDIR/I0/php/video.php >/dev/null
echo "$?" >>$OUTDIR/o7

#I0