#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/my-dir ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cf my-dir.tar my-dir; } &>$OUTDIR/o44

echo "$?" >>$OUTDIR/o44
rm -fr my-dir
tar xf my-dir.tar
diff my-dir/file $INDIR/I5/my-dir/file >/dev/null
echo "$?" >>$OUTDIR/o44


#I5