#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test ./
cp -r $INDIR/I8/test1 ./
cp -r $INDIR/I8/test2 ./
cp -r $INDIR/I8/test3 ./
cp -r $INDIR/I8/test4 ./
cp -r $INDIR/I8/filenamenotcontainingtest ./
cp -r $INDIR/I8/testdir ./

{ timeout -k 9 ${TIMEOUT}s $BIN --create -f test.tar * --exclude='test*'; } &>$OUTDIR/o75

echo "$?" >>$OUTDIR/o75
rm -fr test test1 test2 test3 test4 filenamenotcontainingtest testdir
tar xf test.tar
test -f test
echo "$?" >>$OUTDIR/o75
test -f test1
echo "$?" >>$OUTDIR/o75
test -f test2
echo "$?" >>$OUTDIR/o75
test -f test3
echo "$?" >>$OUTDIR/o75
test -f test4
echo "$?" >>$OUTDIR/o75
test -d testdir
echo "$?" >>$OUTDIR/o75

diff filenamenotcontainingtest $INDIR/I8/filenamenotcontainingtest
echo "$?" >>$OUTDIR/o75



#I8