#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test ./

{ timeout -k 9 ${TIMEOUT}s $BIN cf archive.tar test --owner=0 --group=0; } &>$OUTDIR/o64

echo "$?" >>$OUTDIR/o64
info=`tar -tvf archive.tar | tr -s ' ' | cut -d' ' -f1,2`
echo "${info}" >>$OUTDIR/o64
rm test
tar xf archive.tar
diff test $INDIR/I8/test >/dev/null
echo "$?" >>$OUTDIR/o64






#I8
