#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I0/public_html-14-09-12.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf public_html-14-09-12.tar; } &>$OUTDIR/o1

echo "$?" >>$OUTDIR/o1

diff public_html/videos/views.php $INDIR/I0/public_html/videos/views.php >/dev/null
echo "$?" >>$OUTDIR/o1

diff public_html/videos/index.php $INDIR/I0/public_html/videos/index.php >/dev/null
echo "$?" >>$OUTDIR/o1

diff public_html/videos/logout.php $INDIR/I0/public_html/videos/logout.php >/dev/null
echo "$?" >>$OUTDIR/o1

diff public_html/videos/all_categories.php $INDIR/I0/public_html/videos/all_categories.php >/dev/null
echo "$?" >>$OUTDIR/o1

diff public_html/videos/feeds.xml $INDIR/I0/public_html/videos/feeds.xml >/dev/null
echo "$?" >>$OUTDIR/o1







#I0