#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/ubuntu/stuff ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archive.tar stuff; } &>$OUTDIR/o21

echo "$?" >>$OUTDIR/o21
rm -fr stuff
tar xf archive.tar
diff stuff/test/file1 $INDIR/I2/ubuntu/stuff/test/file1 >/dev/null
echo "$?" >>$OUTDIR/o21
diff stuff/test/file2 $INDIR/I2/ubuntu/stuff/test/file2 >/dev/null
echo "$?" >>$OUTDIR/o21



#I2