#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/archive.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN xf archive.tar --newer-mtime=2020-03-01; } &>$OUTDIR/o653

echo "$?" >>$OUTDIR/o653
diff file2 $INDIR/I8/file2
echo "$?" >>$OUTDIR/o653







#I8