#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test4.tar ./
echo "0987654321" >test2

{ timeout -k 9 ${TIMEOUT}s $BIN -uf test4.tar test2; } &>$OUTDIR/o71

echo "$?" >>$OUTDIR/o71
mv test2 test2.origin
tar xf test4.tar
diff test $INDIR/I8/test >/dev/null
echo "$?" >>$OUTDIR/o71
diff test1 $INDIR/I8/test1 >/dev/null
echo "$?" >>$OUTDIR/o71
diff test2 test2.origin >/dev/null
echo "$?" >>$OUTDIR/o71
diff test3 $INDIR/I8/test3 >/dev/null
echo "$?" >>$OUTDIR/o71



#I8