#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/etc2 ./
cp -r $INDIR/I7/opt2 ./
cp -r $INDIR/I7/home2 ./
CURRDIR=$(pwd)

echo "$CURRDIR/etc2" >tar-include
echo "$CURRDIR/opt2" >>tar-include
echo "$CURRDIR/home2" >>tar-include

echo "$CURRDIR/etc2/sysconfig/kdump" >tar-exclude
echo "$CURRDIR/etc2/sysconfig/foreman" >>tar-exclude

{ timeout -k 9 ${TIMEOUT}s $BIN -cpvf myarchive.tar -T $CURRDIR/tar-include -X $CURRDIR/tar-exclude; } &>$OUTDIR/o59

echo "$?" >>$OUTDIR/o59

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm -fr etc2
rm -fr opt2
rm -fr home2
tar xf myarchive.tar
diff ${leadpath}/etc2/file $INDIR/I7/etc2/file >/dev/null
echo "$?" >>$OUTDIR/o59
diff ${leadpath}/opt2/file $INDIR/I7/opt2/file >/dev/null
echo "$?" >>$OUTDIR/o59
diff ${leadpath}/home2/file $INDIR/I7/home2/file >/dev/null
echo "$?" >>$OUTDIR/o59

test -f ${leadpath}/etc2/sysconfig/kdump
echo "$?" >>$OUTDIR/o59
test -f ${leadpath}/etc2/sysconfig/foreman
echo "$?" >>$OUTDIR/o59


#I7