#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/myarchive.tar ./
mkdir tmp

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf myarchive.tar -C tmp; } &>$OUTDIR/o56

echo "$?" >>$OUTDIR/o56

if [ -f tmp/default.profraw ]; then
    cp tmp/default.profraw ./
fi

diff tmp/home/qxin6/debaug_expt/debaug/benchmark/tar-1.14_template/input.origin/I7/etc/file $INDIR/I7/etc/file >/dev/null
echo "$?" >>$OUTDIR/o56

diff tmp/home/qxin6/debaug_expt/debaug/benchmark/tar-1.14_template/input.origin/I7/anaconda-ks.cfg $INDIR/I7/anaconda-ks.cfg >/dev/null
echo "$?" >>$OUTDIR/o56



#I7