#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/bigfile.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf bigfile.tar; } &>$OUTDIR/o10

echo "$?" >>$OUTDIR/o10
diff bigfile $INDIR/I1/bigfile >/dev/null
echo "$?" >>$OUTDIR/o10



#I1