#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Videos ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -cw -f hugefie.tar ./Videos/*" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o18

echo "$?" >>$OUTDIR/o18
rm -fr ./Videos
tar xf hugefie.tar
diff ./Videos/file $INDIR/I1/Videos/file
echo "$?" >>$OUTDIR/o18

rm run.sh

#I1