#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/archive.tar ./
cp -r $INDIR/I4/todo.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN rvf archive.tar todo.txt; } &>$OUTDIR/o41

echo "$?" >>$OUTDIR/o41
rm *.txt
tar xf archive.tar
diff file1 $INDIR/I4/file1 >/dev/null
echo "$?" >>$OUTDIR/o41
diff file2 $INDIR/I4/file2 >/dev/null
echo "$?" >>$OUTDIR/o41
diff file3 $INDIR/I4/file3 >/dev/null
echo "$?" >>$OUTDIR/o41
diff todo.txt $INDIR/I4/todo.txt >/dev/null
echo "$?" >>$OUTDIR/o41



#I4