#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file.tar ./
cp -r $INDIR/I3/os5.c ./

{ timeout -k 9 ${TIMEOUT}s $BIN rvf file.tar *.c; } &>$OUTDIR/o33

echo "$?" >>$OUTDIR/o33
rm *.c
tar xf file.tar
diff os2.c $INDIR/I3/os2.c
echo "$?" >>$OUTDIR/o33
diff os3.c $INDIR/I3/os3.c
echo "$?" >>$OUTDIR/o33
diff os4.c $INDIR/I3/os4.c
echo "$?" >>$OUTDIR/o33
diff os5.c $INDIR/I3/os5.c
echo "$?" >>$OUTDIR/o33

#I3