#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/file.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f file.tar --delete file1 file2; } &>$OUTDIR/o82

echo "$?" >>$OUTDIR/o82
tar xf file.tar
test -f file1
echo "$?" >>$OUTDIR/o82
test -f file2
echo "$?" >>$OUTDIR/o82
diff file3 $INDIR/I9/file3
echo "$?" >>$OUTDIR/o82
diff file4 $INDIR/I9/file4
echo "$?" >>$OUTDIR/o82
diff file5 $INDIR/I9/file5
echo "$?" >>$OUTDIR/o82
diff file6 $INDIR/I9/file6
echo "$?" >>$OUTDIR/o82


#I9