#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Institution.tar ./
cp -r $INDIR/I1/College ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf Institution.tar ./College/Engineering/top.ppt; } &>$OUTDIR/o120

echo "$?" >>$OUTDIR/o120
rm -fr College
tar xf Institution.tar ./College/Engineering/top.ppt
diff College/Engineering/top.ppt $INDIR/I1/College/Engineering/top.ppt
echo "$?" >>$OUTDIR/o120

#I1