#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN xvf file.tar; } &>$OUTDIR/o29

echo "$?" >>$OUTDIR/o29
diff os2.c $INDIR/I3/os2.c >/dev/null
echo "$?" >>$OUTDIR/o29
diff os3.c $INDIR/I3/os3.c >/dev/null
echo "$?" >>$OUTDIR/o29
diff os4.c $INDIR/I3/os4.c >/dev/null
echo "$?" >>$OUTDIR/o29


#I3