#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/archive.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN xf archive.tar --preserve-permissions; } &>$OUTDIR/o664

echo "$?" >>$OUTDIR/o664
info=`ls -l | sed -n '1!p' | tr -s ' ' | cut -d' ' -f1,3,4`
echo ${info} >>$OUTDIR/o664
diff filenamenotcontainingtest $INDIR/I8/filenamenotcontainingtest
echo "$?" >>$OUTDIR/o664
diff test $INDIR/I8/test
echo "$?" >>$OUTDIR/o664
diff file2 $INDIR/I8/file2
echo "$?" >>$OUTDIR/o664







#I8