#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/some_archive.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xf some_archive.tar -C .; } &>$OUTDIR/o47

echo "$?" >>$OUTDIR/o47
diff some_archive/file $INDIR/I5/some_archive/file
echo "$?" >>$OUTDIR/o47


#I5