#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/dir1 ./
cp -r $INDIR/I9/dir2 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf dir.tar dir1 dir2; } &>$OUTDIR/o78

echo "$?" >>$OUTDIR/o78
rm -fr dir1 dir2
tar xf dir.tar
diff dir1/file $INDIR/I9/dir1/file
echo "$?" >>$OUTDIR/o78
diff dir2/file $INDIR/I9/dir2/file
echo "$?" >>$OUTDIR/o78

#I9