#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/my-file.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cf archive.tar my-file.txt; } &>$OUTDIR/o45

echo "$?" >>$OUTDIR/o45
rm -fr my-file.txt
tar xf archive.tar
diff my-file.txt $INDIR/I5/my-file.txt >/dev/null
echo "$?" >>$OUTDIR/o45


#I5