#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xf test.tar; } &>$OUTDIR/o73

echo "$?" >>$OUTDIR/o73
diff test $INDIR/I8/test >/dev/null
echo "$?" >>$OUTDIR/o73
diff test1 $INDIR/I8/test1 >/dev/null
echo "$?" >>$OUTDIR/o73
diff test2 $INDIR/I8/test2 >/dev/null
echo "$?" >>$OUTDIR/o73
diff test3 $INDIR/I8/test3 >/dev/null
echo "$?" >>$OUTDIR/o73
diff test4 $INDIR/I8/test4 >/dev/null
echo "$?" >>$OUTDIR/o73



#I8