#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/file.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf file.tar; } &>$OUTDIR/o80

echo "$?" >>$OUTDIR/o80
diff file1 $INDIR/I9/file1
echo "$?" >>$OUTDIR/o80
diff file2 $INDIR/I9/file2
echo "$?" >>$OUTDIR/o80
diff file3 $INDIR/I9/file3
echo "$?" >>$OUTDIR/o80
diff file4 $INDIR/I9/file4
echo "$?" >>$OUTDIR/o80
diff file5 $INDIR/I9/file5
echo "$?" >>$OUTDIR/o80
diff file6 $INDIR/I9/file6
echo "$?" >>$OUTDIR/o80

#I9