#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Institution.tar ./
cp -r $INDIR/I1/College ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf Institution.tar ./College/Engineering/top.ppt; } &>$OUTDIR/o12

echo "$?" >>$OUTDIR/o12
rm -fr College
tar xf Institution.tar ./College/Engineering/top.ppt
diff College/Engineering/top.ppt $INDIR/I1/College/Engineering/top.ppt >/dev/null
echo "$?" >>$OUTDIR/o12

#I1
