#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I0/public_html-14-09-12.tar ./
mkdir tmp

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf public_html-14-09-12.tar -C tmp; } &>$OUTDIR/o2

echo "$?" >>$OUTDIR/o2

if [ -f tmp/default.profraw ]; then
    cp tmp/default.profraw ./ #This is important!
fi

diff tmp/public_html/videos/views.php $INDIR/I0/public_html/videos/views.php >/dev/null
echo "$?" >>$OUTDIR/o2

diff tmp/public_html/videos/index.php $INDIR/I0/public_html/videos/index.php >/dev/null
echo "$?" >>$OUTDIR/o2

diff tmp/public_html/videos/logout.php $INDIR/I0/public_html/videos/logout.php >/dev/null
echo "$?" >>$OUTDIR/o2

diff tmp/public_html/videos/all_categories.php $INDIR/I0/public_html/videos/all_categories.php >/dev/null
echo "$?" >>$OUTDIR/o2

diff tmp/public_html/videos/feeds.xml $INDIR/I0/public_html/videos/feeds.xml >/dev/null
echo "$?" >>$OUTDIR/o2


#I0
