#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/file.tar ./

{ timeout -k 9 ${TIMEOUT}s $BIN xvf file.tar os2.c os3.c; } &>$OUTDIR/o32

echo "$?" >>$OUTDIR/o32

diff os2.c $INDIR/I3/os2.c >/dev/null
echo "$?" >>$OUTDIR/o32
diff os3.c $INDIR/I3/os3.c >/dev/null
echo "$?" >>$OUTDIR/o32

#I3