#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/ubuntu/Downloads ./
cp -r $INDIR/I2/ubuntu/Documents ./
CURRDIR=$(pwd)
mkdir -p $(pwd)/usr/local/mytest
{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archive.tar $CURRDIR/Downloads $(pwd)/usr/local/mytest $CURRDIR/Documents; } &>$OUTDIR/o23

echo "$?" >>$OUTDIR/o23

leadpath=`echo $CURRDIR | cut -c2-` #First "/" is ignored for compression
rm -fr Downloads
rm -fr Documents

tar xf archive.tar
diff ${leadpath}/Downloads/song.mp3 $INDIR/I2/ubuntu/Downloads/song.mp3
echo "$?" >>$OUTDIR/o23
diff ${leadpath}/Downloads/video.mp4 $INDIR/I2/ubuntu/Downloads/video.mp4
echo "$?" >>$OUTDIR/o23
diff ${leadpath}/Downloads/image.png $INDIR/I2/ubuntu/Downloads/image.png
echo "$?" >>$OUTDIR/o23

diff ${leadpath}/Documents/notes.txt $INDIR/I2/ubuntu/Documents/notes.txt
echo "$?" >>$OUTDIR/o23

diff $(pwd)/usr/local/mytest/file $(pwd)/usr/local/mytest/file
echo "$?" >>$OUTDIR/o23



#I2
