#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/Book.tar ./
cp -r $INDIR/I1/pageone.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rv -f Book.tar pageone.txt; } &>$OUTDIR/o20

echo "$?" >>$OUTDIR/o20
rm pageone.txt
tar xf Book.tar pageone.txt
diff pageone.txt $INDIR/I1/pageone.txt
echo "$?" >>$OUTDIR/o20

#I1