#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/file1 ./
cp -r $INDIR/I4/file2 ./
cp -r $INDIR/I4/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN cfv archive.tar file1 file2 file3; } &>$OUTDIR/o38

echo "$?" >>$OUTDIR/o38
rm file*
tar xf archive.tar
diff file1 $INDIR/I4/file1 >/dev/null
echo "$?" >>$OUTDIR/o38
diff file2 $INDIR/I4/file2 >/dev/null
echo "$?" >>$OUTDIR/o38
diff file3 $INDIR/I4/file3 >/dev/null
echo "$?" >>$OUTDIR/o38


#I4