#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I4/todo.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN cfv archive.tar *.txt; } &>$OUTDIR/o40

echo "$?" >>$OUTDIR/o40
rm *.txt
tar xf archive.tar
diff todo.txt $INDIR/I4/todo.txt
echo "$?" >>$OUTDIR/o40



#I4