#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/os2.c ./
cp -r $INDIR/I3/os3.c ./
cp -r $INDIR/I3/os4.c ./

{ timeout -k 9 ${TIMEOUT}s $BIN cvf file.tar *.c; } &>$OUTDIR/o28

echo "$?" >>$OUTDIR/o28
rm -f *.c
tar xf file.tar
diff os2.c $INDIR/I3/os2.c
echo "$?" >>$OUTDIR/o28
diff os3.c $INDIR/I3/os3.c
echo "$?" >>$OUTDIR/o28
diff os4.c $INDIR/I3/os4.c
echo "$?" >>$OUTDIR/o28


#I3