#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4
mkdir -p $(pwd)/usr/local/mytest
touch $(pwd)/usr/local/mytest/file
{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archive.tar $(pwd)/usr/local/mytest; } &>$OUTDIR/o22

echo "$?" >>$OUTDIR/o22
tar xf archive.tar
diff $(pwd)/usr/local/mytest/file $(pwd)/usr/local/mytest/file >/dev/null
echo "$?" >>$OUTDIR/o22




#I2
