#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/archive.tar ./
mkdir tmp

{ timeout -k 9 ${TIMEOUT}s $BIN -xvf archive.tar -C tmp; } &>$OUTDIR/o27

echo "$?" >>$OUTDIR/o27

if [ -f tmp/default.profraw ]; then
    cp tmp/default.profraw ./ #Important
fi

diff tmp/stuff/test/file1 $INDIR/I2/ubuntu/stuff/test/file1
echo "$?" >>$OUTDIR/o27
diff tmp/stuff/test/file2 $INDIR/I2/ubuntu/stuff/test/file2
echo "$?" >>$OUTDIR/o27



#I2