#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/test.tar ./
cp -r $INDIR/I8/filenamenotcontainingtest ./

{ timeout -k 9 ${TIMEOUT}s $BIN --append -f test.tar filenamenotcontainingtest; } &>$OUTDIR/o68

echo "$?" >>$OUTDIR/o68
rm filenamenotcontainingtest
tar xf test.tar
diff test $INDIR/I8/test >/dev/null
echo "$?" >>$OUTDIR/o68
diff test1 $INDIR/I8/test1 >/dev/null
echo "$?" >>$OUTDIR/o68
diff test2 $INDIR/I8/test2 >/dev/null
echo "$?" >>$OUTDIR/o68
diff test3 $INDIR/I8/test3 >/dev/null
echo "$?" >>$OUTDIR/o68
diff test4 $INDIR/I8/test4 >/dev/null
echo "$?" >>$OUTDIR/o68
diff filenamenotcontainingtest $INDIR/I8/filenamenotcontainingtest >/dev/null
echo "$?" >>$OUTDIR/o68


#I8