#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I6/file1 ./
cp -r $INDIR/I6/file2 ./
cp -r $INDIR/I6/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -cvf archiveToCreate.tar file1 file2 file3; } &>$OUTDIR/o48

echo "$?" >>$OUTDIR/o48
rm -fr file*
tar xf archiveToCreate.tar
diff file1 $INDIR/I6/file1 >/dev/null
echo "$?" >>$OUTDIR/o48
diff file2 $INDIR/I6/file2 >/dev/null
echo "$?" >>$OUTDIR/o48
diff file3 $INDIR/I6/file3 >/dev/null
echo "$?" >>$OUTDIR/o48


#I6