#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I9/file.tar ./
cp -r $INDIR/I9/file7 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf file.tar file7; } &>$OUTDIR/o81

echo "$?" >>$OUTDIR/o81
rm -fr file7
tar xf file.tar
diff file1 $INDIR/I9/file1 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file2 $INDIR/I9/file2 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file3 $INDIR/I9/file3 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file4 $INDIR/I9/file4 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file5 $INDIR/I9/file5 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file6 $INDIR/I9/file6 >/dev/null
echo "$?" >>$OUTDIR/o81
diff file7 $INDIR/I9/file7 >/dev/null
echo "$?" >>$OUTDIR/o81

#I9