#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I2/-store ./

{ timeout -k 9 ${TIMEOUT}s $BIN -- \-store; } &>$OUTDIR/o38

echo "$?" >>$OUTDIR/o38
test -f -store
echo "$?" >>$OUTDIR/o38


