#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/dir ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r dir; } &>$OUTDIR/o45

echo "$?" >>$OUTDIR/o45
test -d dir
echo "$?" >>$OUTDIR/o45
test -f dir/file
echo "$?" >>$OUTDIR/o45



