#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I7/try2 ./
cp $INDIR/I7/try3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN try2 try3; } &>$OUTDIR/o69

echo "$?" >>$OUTDIR/o69
test -f try2
echo "$?" >>$OUTDIR/o69
test -f try3
echo "$?" >>$OUTDIR/o69


