#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

mkdir appdata #Made empty

{ timeout -k 9 ${TIMEOUT}s $BIN -d appdata; } &>$OUTDIR/o26

echo "$?" >>$OUTDIR/o26
test -d appdata
echo "$?" >>$OUTDIR/o26
