#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I5/voltron.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN voltron.txt; } &>$OUTDIR/o53

echo "$?" >>$OUTDIR/o53
test -f voltron.txt
echo "$?" >>$OUTDIR/o53


