#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I8/files ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -rvi files/" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o80

echo "$?" >>$OUTDIR/o80
test -d files
echo "$?" >>$OUTDIR/o80
test -d files/a-test
echo "$?" >>$OUTDIR/o80
test -d files/b-test
echo "$?" >>$OUTDIR/o80
test -d files/c-test
echo "$?" >>$OUTDIR/o80

for i in a b c; do
    for j in 1 2 3; do
	test -f files/${i}-test-${j}
	echo "$?" >>$OUTDIR/o80
    done
done


