#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I0/b.txt ./
cp $INDIR/I0/c.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN b.txt c.txt; } &>$OUTDIR/o1

echo "$?" >>$OUTDIR/o1
test -f b.txt
echo "$?" >>$OUTDIR/o1
test -f c.txt
echo "$?" >>$OUTDIR/o1
