#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I5/decepticons ./

{ timeout -k 9 ${TIMEOUT}s $BIN -r -v decepticons/; } &>$OUTDIR/o57

echo "$?" >>$OUTDIR/o57
test -d decepticons
echo "$?" >>$OUTDIR/o57
test -f decepticons/shockwave.txt
echo "$?" >>$OUTDIR/o57
test -f decepticons/soundwave.txt
echo "$?" >>$OUTDIR/o57
test -f decepticons/starscream.txt
echo "$?" >>$OUTDIR/o57


