#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/file1 ./
cp $INDIR/I3/file2 ./
cp $INDIR/I3/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1 file2 file3; } &>$OUTDIR/o42

echo "$?" >>$OUTDIR/o42
test -f file1
echo "$?" >>$OUTDIR/o42
test -f file2
echo "$?" >>$OUTDIR/o42
test -f file3
echo "$?" >>$OUTDIR/o42


