#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I2/dbstore ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -ri dbstore/" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o28

echo "$?" >>$OUTDIR/o28
test -d dbstore
echo "$?" >>$OUTDIR/o28
test -f dbstore/file1.log
echo "$?" >>$OUTDIR/o28
test -f dbstore/file2.log
echo "$?" >>$OUTDIR/o28
test -f dbstore/file3.log
echo "$?" >>$OUTDIR/o28
test -f dbstore/service
echo "$?" >>$OUTDIR/o28

rm run.sh
