#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I9/file1 ./
cp $INDIR/I9/file2 ./
cp $INDIR/I9/file3 ./

{ timeout -k 9 ${TIMEOUT}s $BIN file1 file2 file3; } &>$OUTDIR/o81

echo "$?" >>$OUTDIR/o81
test -f file1
echo "$?" >>$OUTDIR/o81
test -f file2
echo "$?" >>$OUTDIR/o81
test -f file3
echo "$?" >>$OUTDIR/o81


