#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I3/file1 ./
cp $INDIR/I3/file2 ./
cp $INDIR/I3/file3 ./
cp $INDIR/I3/file4 ./

echo '#!/bin/bash' >run.sh
echo "" >>run.sh
echo "echo y | $BIN -I file1 file2 file3 file4" >>run.sh
chmod 700 run.sh

{ timeout -k 9 ${TIMEOUT}s ./run.sh; } &>$OUTDIR/o47

echo "$?" >>$OUTDIR/o47
test -f file1
echo "$?" >>$OUTDIR/o47
test -f file2
echo "$?" >>$OUTDIR/o47
test -f file3
echo "$?" >>$OUTDIR/o47
test -f file4
echo "$?" >>$OUTDIR/o47

rm run.sh
