#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/dir2 ./

{ timeout -k 9 ${TIMEOUT}s $BIN -dr dir2; } &>$OUTDIR/o73

echo "$?" >>$OUTDIR/o73
test -d dir2
echo "$?" >>$OUTDIR/o73
test -f dir2/file1
echo "$?" >>$OUTDIR/o73
test -f dir2/file2
echo "$?" >>$OUTDIR/o73
test -f dir2/file3
echo "$?" >>$OUTDIR/o73


