#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I1/mydirectory ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf mydirectory; } &>$OUTDIR/o22

echo "$?" >>$OUTDIR/o22
test -d mydirectory
echo "$?" >>$OUTDIR/o22
test -f mydirectory/file
echo "$?" >>$OUTDIR/o22
