#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I7/dir1 ./

#Intended failure
{ timeout -k 9 ${TIMEOUT}s $BIN -d dir1; } &>$OUTDIR/o71

echo "$?" >>$OUTDIR/o71
test -d dir1
echo "$?" >>$OUTDIR/o71
test -f dir1/file1
echo "$?" >>$OUTDIR/o71


