#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN myfile.txt; } &>$OUTDIR/o15

echo "$?" >>$OUTDIR/o15
test -f myfile.txt
echo "$?" >>$OUTDIR/o15
