#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I1/myfile.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -f *; } &>$OUTDIR/o18

echo "$?" >>$OUTDIR/o18
test -f myfile.txt
echo "$?" >>$OUTDIR/o18

