#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I8/test.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN -v test.txt; } &>$OUTDIR/o75

echo "$?" >>$OUTDIR/o75
test -f test.txt
echo "$?" >>$OUTDIR/o75


