#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/accounts.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN accounts.txt; } &>$OUTDIR/o49

echo "$?" >>$OUTDIR/o49
test -f accounts.txt
echo "$?" >>$OUTDIR/o49


