#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp $INDIR/I4/*.txt ./

{ timeout -k 9 ${TIMEOUT}s $BIN *.txt; } &>$OUTDIR/o52

echo "$?" >>$OUTDIR/o52
test -f accounts.txt
echo "$?" >>$OUTDIR/o52
test -f test.txt
echo "$?" >>$OUTDIR/o52


