#!/bin/bash

BIN=$1
OUTDIR=$2
TIMEOUT=$3
INDIR=$4

cp -r $INDIR/I3/dir ./

{ timeout -k 9 ${TIMEOUT}s $BIN -rf dir; } &>$OUTDIR/o48

echo "$?" >>$OUTDIR/o48
test -d dir
echo "$?" >>$OUTDIR/o48
test -f dir/file
echo "$?" >>$OUTDIR/o48
